// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: multitenant/mtinfopb/info.proto

package mtinfopb

import (
	encoding_binary "encoding/binary"
	fmt "fmt"
	kvpb "github.com/cockroachdb/cockroach/pkg/kv/kvpb"
	tenantcapabilitiespb "github.com/cockroachdb/cockroach/pkg/multitenant/tenantcapabilities/tenantcapabilitiespb"
	github_com_cockroachdb_cockroach_pkg_roachpb "github.com/cockroachdb/cockroach/pkg/roachpb"
	github_com_cockroachdb_cockroach_pkg_sql_catalog_catpb "github.com/cockroachdb/cockroach/pkg/sql/catalog/catpb"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// The state of the tenant's logical keyspace (DEPRECATED).
// This enum is only used when the data_state column is NULL.
type ProtoInfo_DeprecatedDataState int32

const (
	// Tenant data is ready and SQL servers can access it.
	// DEPRECATED. Use DataStateReady.
	ProtoInfo_READY ProtoInfo_DeprecatedDataState = 0
	// Tenant data is being added. Not available for SQL sessions.
	// DEPRECATED. Use DataStateAdd.
	ProtoInfo_ADD ProtoInfo_DeprecatedDataState = 1
	// Tenant data is being dropped. Not available for SQL sessions.
	// DEPRECATED. Use DataStateDrop.
	ProtoInfo_DROP ProtoInfo_DeprecatedDataState = 2
)

var ProtoInfo_DeprecatedDataState_name = map[int32]string{
	0: "READY",
	1: "ADD",
	2: "DROP",
}

var ProtoInfo_DeprecatedDataState_value = map[string]int32{
	"READY": 0,
	"ADD":   1,
	"DROP":  2,
}

func (x ProtoInfo_DeprecatedDataState) Enum() *ProtoInfo_DeprecatedDataState {
	p := new(ProtoInfo_DeprecatedDataState)
	*p = x
	return p
}

func (x ProtoInfo_DeprecatedDataState) String() string {
	return proto.EnumName(ProtoInfo_DeprecatedDataState_name, int32(x))
}

func (x *ProtoInfo_DeprecatedDataState) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ProtoInfo_DeprecatedDataState_value, data, "ProtoInfo_DeprecatedDataState")
	if err != nil {
		return err
	}
	*x = ProtoInfo_DeprecatedDataState(value)
	return nil
}

func (ProtoInfo_DeprecatedDataState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_22ea1ce3469aae16, []int{0, 0}
}

// ProtoInfo represents the metadata for a tenant as
// stored in the "info" column of the "system.tenants" table.
type ProtoInfo struct {
	// ID is the internal numeric identifier of the tenant (DEPRECATED).
	// This field is redundant with the id column in system.tenants.
	DeprecatedID uint64 `protobuf:"varint,1,opt,name=deprecated_id,json=deprecatedId" json:"deprecated_id"`
	// DeprecatedDataState is the state of the tenant's keyspace (DEPRECATED).
	DeprecatedDataState ProtoInfo_DeprecatedDataState `protobuf:"varint,2,opt,name=deprecated_data_state,json=deprecatedDataState,enum=cockroach.multitenant.ProtoInfo_DeprecatedDataState" json:"deprecated_data_state"`
	// DroppedName is the name the tenant had before DROP VIRTUAL
	// CLUSTER was run on the tenant. It should be empty for active or
	// adding tenants.
	DroppedName github_com_cockroachdb_cockroach_pkg_roachpb.TenantName `protobuf:"bytes,3,opt,name=dropped_name,json=droppedName,casttype=github.com/cockroachdb/cockroach/pkg/roachpb.TenantName" json:"dropped_name"`
	// TenantReplicationJobID is set if this tenant is the target tenant
	// of a running tenant replication job.
	TenantReplicationJobID github_com_cockroachdb_cockroach_pkg_sql_catalog_catpb.JobID `protobuf:"varint,4,opt,name=tenant_replication_job_id,json=tenantReplicationJobId,casttype=github.com/cockroachdb/cockroach/pkg/sql/catalog/catpb.JobID" json:"tenant_replication_job_id"`
	// Capabilities encapsulate a set of capabilities that a specific tenant
	// possesses.
	Capabilities tenantcapabilitiespb.TenantCapabilities `protobuf:"bytes,5,opt,name=capabilities" json:"capabilities"`
}

func (m *ProtoInfo) Reset()         { *m = ProtoInfo{} }
func (m *ProtoInfo) String() string { return proto.CompactTextString(m) }
func (*ProtoInfo) ProtoMessage()    {}
func (*ProtoInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_22ea1ce3469aae16, []int{0}
}
func (m *ProtoInfo) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ProtoInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *ProtoInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProtoInfo.Merge(m, src)
}
func (m *ProtoInfo) XXX_Size() int {
	return m.Size()
}
func (m *ProtoInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ProtoInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ProtoInfo proto.InternalMessageInfo

// SQLInfo contain the additional tenant metadata from the other
// columns in system.tenants not otherwise encoded in ProtoInfo.
type SQLInfo struct {
	ID uint64 `protobuf:"varint,1,opt,name=id" json:"id"`
	// Copy of the name column in system.tenants.
	Name github_com_cockroachdb_cockroach_pkg_roachpb.TenantName `protobuf:"bytes,2,opt,name=name,casttype=github.com/cockroachdb/cockroach/pkg/roachpb.TenantName" json:"name"`
	// Copy of the data_state column in system.tenants.
	DataState TenantDataState `protobuf:"varint,3,opt,name=data_state,json=dataState,casttype=TenantDataState" json:"data_state"`
	// Copy of the service_mode column in system.tenants.
	ServiceMode TenantServiceMode `protobuf:"varint,4,opt,name=service_mode,json=serviceMode,casttype=TenantServiceMode" json:"service_mode"`
}

func (m *SQLInfo) Reset()         { *m = SQLInfo{} }
func (m *SQLInfo) String() string { return proto.CompactTextString(m) }
func (*SQLInfo) ProtoMessage()    {}
func (*SQLInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_22ea1ce3469aae16, []int{1}
}
func (m *SQLInfo) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SQLInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *SQLInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SQLInfo.Merge(m, src)
}
func (m *SQLInfo) XXX_Size() int {
	return m.Size()
}
func (m *SQLInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_SQLInfo.DiscardUnknown(m)
}

var xxx_messageInfo_SQLInfo proto.InternalMessageInfo

// UsageInfo contains metadata related to cost control and consumption. In a
// running cluster, this data is stored in the system.tenant_usage table.
// Each field corresponds has a corresponding column in that table.
type UsageInfo struct {
	RUBurstLimit float64 `protobuf:"fixed64,1,opt,name=ru_burst_limit,json=ruBurstLimit" json:"ru_burst_limit"`
	RURefillRate float64 `protobuf:"fixed64,2,opt,name=ru_refill_rate,json=ruRefillRate" json:"ru_refill_rate"`
	RUCurrent    float64 `protobuf:"fixed64,3,opt,name=ru_current,json=ruCurrent" json:"ru_current"`
	// All-time consumption for this tenant. Each field has a corresponding column
	// in system.tenant_usage.
	Consumption kvpb.TenantConsumption `protobuf:"bytes,4,opt,name=consumption" json:"consumption"`
}

func (m *UsageInfo) Reset()         { *m = UsageInfo{} }
func (m *UsageInfo) String() string { return proto.CompactTextString(m) }
func (*UsageInfo) ProtoMessage()    {}
func (*UsageInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_22ea1ce3469aae16, []int{2}
}
func (m *UsageInfo) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *UsageInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *UsageInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UsageInfo.Merge(m, src)
}
func (m *UsageInfo) XXX_Size() int {
	return m.Size()
}
func (m *UsageInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_UsageInfo.DiscardUnknown(m)
}

var xxx_messageInfo_UsageInfo proto.InternalMessageInfo

// SettingOverride represents a cluster setting override for one tenant.
type SettingOverride struct {
	Name      string  `protobuf:"bytes,1,opt,name=name" json:"name"`
	Value     string  `protobuf:"bytes,2,opt,name=value" json:"value"`
	ValueType string  `protobuf:"bytes,3,opt,name=value_type,json=valueType" json:"value_type"`
	Reason    *string `protobuf:"bytes,4,opt,name=reason" json:"reason,omitempty"`
}

func (m *SettingOverride) Reset()         { *m = SettingOverride{} }
func (m *SettingOverride) String() string { return proto.CompactTextString(m) }
func (*SettingOverride) ProtoMessage()    {}
func (*SettingOverride) Descriptor() ([]byte, []int) {
	return fileDescriptor_22ea1ce3469aae16, []int{3}
}
func (m *SettingOverride) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SettingOverride) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *SettingOverride) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SettingOverride.Merge(m, src)
}
func (m *SettingOverride) XXX_Size() int {
	return m.Size()
}
func (m *SettingOverride) XXX_DiscardUnknown() {
	xxx_messageInfo_SettingOverride.DiscardUnknown(m)
}

var xxx_messageInfo_SettingOverride proto.InternalMessageInfo

// TenantInfoWithUsage contains the information for a tenant in a multi-tenant
// cluster plus metadata related to cost control and consumption and setting overrides.
type TenantInfoWithUsage struct {
	ProtoInfo        `protobuf:"bytes,1,opt,name=info,embedded=info" json:"info"`
	Usage            *UsageInfo `protobuf:"bytes,2,opt,name=usage" json:"usage,omitempty"`
	SQLInfo          `protobuf:"bytes,3,opt,name=extra_columns,json=extraColumns,embedded=extra_columns" json:"extra_columns"`
	SettingOverrides []*SettingOverride `protobuf:"bytes,4,rep,name=setting_overrides,json=settingOverrides" json:"setting_overrides,omitempty"`
}

func (m *TenantInfoWithUsage) Reset()         { *m = TenantInfoWithUsage{} }
func (m *TenantInfoWithUsage) String() string { return proto.CompactTextString(m) }
func (*TenantInfoWithUsage) ProtoMessage()    {}
func (*TenantInfoWithUsage) Descriptor() ([]byte, []int) {
	return fileDescriptor_22ea1ce3469aae16, []int{4}
}
func (m *TenantInfoWithUsage) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *TenantInfoWithUsage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *TenantInfoWithUsage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TenantInfoWithUsage.Merge(m, src)
}
func (m *TenantInfoWithUsage) XXX_Size() int {
	return m.Size()
}
func (m *TenantInfoWithUsage) XXX_DiscardUnknown() {
	xxx_messageInfo_TenantInfoWithUsage.DiscardUnknown(m)
}

var xxx_messageInfo_TenantInfoWithUsage proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("cockroach.multitenant.ProtoInfo_DeprecatedDataState", ProtoInfo_DeprecatedDataState_name, ProtoInfo_DeprecatedDataState_value)
	proto.RegisterType((*ProtoInfo)(nil), "cockroach.multitenant.ProtoInfo")
	proto.RegisterType((*SQLInfo)(nil), "cockroach.multitenant.SQLInfo")
	proto.RegisterType((*UsageInfo)(nil), "cockroach.multitenant.UsageInfo")
	proto.RegisterType((*SettingOverride)(nil), "cockroach.multitenant.SettingOverride")
	proto.RegisterType((*TenantInfoWithUsage)(nil), "cockroach.multitenant.TenantInfoWithUsage")
}

func init() { proto.RegisterFile("multitenant/mtinfopb/info.proto", fileDescriptor_22ea1ce3469aae16) }

var fileDescriptor_22ea1ce3469aae16 = []byte{
	// 872 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x55, 0x4d, 0x6f, 0x1b, 0x45,
	0x18, 0xf6, 0x38, 0x0e, 0xad, 0xc7, 0x4e, 0x9b, 0x4c, 0xda, 0xe0, 0xe6, 0x60, 0x5b, 0x01, 0x21,
	0x9f, 0xbc, 0xc8, 0xa0, 0xa2, 0x56, 0x55, 0x51, 0x37, 0x0b, 0x92, 0x51, 0x4a, 0xcb, 0xb8, 0x11,
	0x02, 0x24, 0x56, 0xb3, 0xbb, 0x13, 0x67, 0xc8, 0xee, 0xce, 0x32, 0x3b, 0x6b, 0xd1, 0x9f, 0x00,
	0x27, 0xae, 0xdc, 0xf8, 0x17, 0xfc, 0x85, 0x1c, 0x73, 0xac, 0x84, 0x64, 0x81, 0x73, 0xe1, 0x17,
	0x70, 0xe8, 0x09, 0xcd, 0x47, 0xbc, 0x6b, 0xe1, 0x88, 0x1e, 0x38, 0xed, 0xfb, 0xf5, 0xbc, 0x1f,
	0xcf, 0xfb, 0x8e, 0x0d, 0x7b, 0x49, 0x11, 0x4b, 0x26, 0x69, 0x4a, 0x52, 0xe9, 0x24, 0x92, 0xa5,
	0x27, 0x3c, 0x0b, 0x1c, 0xf5, 0x19, 0x66, 0x82, 0x4b, 0x8e, 0xee, 0x86, 0x3c, 0x3c, 0x13, 0x9c,
	0x84, 0xa7, 0xc3, 0x4a, 0xe8, 0xfe, 0x9d, 0x29, 0x9f, 0x72, 0x1d, 0xe1, 0x28, 0xc9, 0x04, 0xef,
	0xef, 0x9c, 0xcd, 0x9c, 0xb3, 0x59, 0x16, 0x38, 0x24, 0x63, 0xd6, 0xf4, 0x69, 0xb5, 0x80, 0xf9,
	0x84, 0x24, 0x23, 0x01, 0x8b, 0x99, 0x64, 0x34, 0x5f, 0x63, 0xca, 0x02, 0xa7, 0xaa, 0x9a, 0x3c,
	0x07, 0xbf, 0x37, 0x60, 0xf3, 0xb9, 0x92, 0xc6, 0xe9, 0x09, 0x47, 0x0f, 0xe0, 0x56, 0x44, 0x33,
	0x41, 0x43, 0x22, 0x69, 0xe4, 0xb3, 0xa8, 0x03, 0xfa, 0x60, 0xd0, 0x70, 0xef, 0x9c, 0xcf, 0x7b,
	0xb5, 0xc5, 0xbc, 0xd7, 0xf6, 0x96, 0xce, 0xb1, 0x87, 0xdb, 0x65, 0xe8, 0x38, 0x42, 0x29, 0xbc,
	0x5b, 0x81, 0x46, 0x44, 0x12, 0x3f, 0x97, 0x44, 0xd2, 0x4e, 0xbd, 0x0f, 0x06, 0xb7, 0x46, 0x1f,
	0x0e, 0xd7, 0x0e, 0x3c, 0x5c, 0xd6, 0x1e, 0x96, 0xb9, 0x3d, 0x22, 0xc9, 0x44, 0x61, 0xdd, 0x86,
	0x2a, 0x8c, 0x77, 0xa3, 0x7f, 0xbb, 0x50, 0x00, 0xdb, 0x91, 0xe0, 0x59, 0x46, 0x23, 0x3f, 0x25,
	0x09, 0xed, 0x6c, 0xf4, 0xc1, 0xa0, 0xe9, 0x7e, 0xac, 0x00, 0xaf, 0xe7, 0xbd, 0x8f, 0xa6, 0x4c,
	0x9e, 0x16, 0xc1, 0x30, 0xe4, 0x89, 0xb3, 0x2c, 0x1c, 0x05, 0xa5, 0xec, 0x64, 0x67, 0x53, 0x47,
	0x4b, 0x59, 0x30, 0x7c, 0xa1, 0x7b, 0xf9, 0x9c, 0x24, 0x14, 0xb7, 0x6c, 0x52, 0xa5, 0xa0, 0x5f,
	0x00, 0xbc, 0x67, 0xfa, 0xf4, 0x05, 0xcd, 0x62, 0x16, 0x12, 0xc9, 0x78, 0xea, 0x7f, 0xc7, 0x03,
	0xc5, 0x4d, 0xa3, 0x0f, 0x06, 0x1b, 0xee, 0xb7, 0x96, 0x9b, 0x3d, 0x93, 0x04, 0x97, 0x71, 0x9f,
	0xf1, 0x60, 0xec, 0xbd, 0x9e, 0xf7, 0x1e, 0xbd, 0x51, 0x2f, 0xf9, 0xf7, 0xb1, 0x13, 0x12, 0x49,
	0x62, 0x3e, 0x55, 0xdf, 0x2c, 0x18, 0x6a, 0x3c, 0xde, 0x93, 0xeb, 0xf2, 0x46, 0xe8, 0x14, 0xb6,
	0xab, 0xeb, 0xec, 0x6c, 0xf6, 0xc1, 0xa0, 0x35, 0x7a, 0x7c, 0x0d, 0xcd, 0xeb, 0xce, 0xc1, 0x8e,
	0x7d, 0x58, 0x31, 0x5a, 0xc2, 0x57, 0x32, 0x1f, 0x7c, 0x00, 0x77, 0xd7, 0xec, 0x06, 0x35, 0xe1,
	0x26, 0xfe, 0xe4, 0x89, 0xf7, 0xd5, 0x76, 0x0d, 0xdd, 0x80, 0x1b, 0x4f, 0x3c, 0x6f, 0x1b, 0xa0,
	0x9b, 0xb0, 0xe1, 0xe1, 0x67, 0xcf, 0xb7, 0xeb, 0x0f, 0x1b, 0x7f, 0xfd, 0xda, 0x03, 0x07, 0x7f,
	0x03, 0x78, 0x63, 0xf2, 0xc5, 0x91, 0xbe, 0xad, 0x7d, 0x58, 0x5f, 0x1e, 0x14, 0xb4, 0xa4, 0xd5,
	0xc7, 0x1e, 0xae, 0xb3, 0x08, 0x4d, 0x60, 0x43, 0x2f, 0xb1, 0xfe, 0xff, 0x2c, 0x51, 0x27, 0x43,
	0xf7, 0x21, 0xac, 0x9c, 0xa1, 0xba, 0x8f, 0x2d, 0xf7, 0x6d, 0x9b, 0xfa, 0xb6, 0x89, 0x5e, 0x4e,
	0x83, 0x9b, 0xd1, 0x72, 0xb0, 0x47, 0xb0, 0x9d, 0x53, 0x31, 0x63, 0x21, 0xf5, 0x13, 0x1e, 0x51,
	0xbd, 0xe7, 0x2d, 0xf7, 0x9e, 0x45, 0xee, 0x18, 0xe4, 0xc4, 0x44, 0x3c, 0xe5, 0x11, 0xc5, 0xad,
	0xbc, 0x54, 0xec, 0xe0, 0x3f, 0xd6, 0x61, 0xf3, 0x38, 0x27, 0x53, 0xaa, 0x47, 0x7f, 0x08, 0x6f,
	0x89, 0xc2, 0x0f, 0x0a, 0x91, 0x4b, 0x3f, 0x66, 0x09, 0x93, 0x9a, 0x06, 0x50, 0xbe, 0x2b, 0x7c,
	0xec, 0x2a, 0xe7, 0x91, 0xf2, 0xe1, 0xb6, 0x28, 0x4a, 0xcd, 0x62, 0x05, 0x3d, 0x61, 0x71, 0xec,
	0x8b, 0xab, 0x07, 0xb5, 0x82, 0xc5, 0xda, 0x89, 0xd5, 0x18, 0x6d, 0x51, 0x94, 0x1a, 0x7a, 0x1f,
	0x42, 0x51, 0xf8, 0x61, 0x21, 0x04, 0x4d, 0xa5, 0x66, 0x00, 0xb8, 0x3b, 0x16, 0xd7, 0xc4, 0xc7,
	0x87, 0xc6, 0x81, 0x9b, 0xa2, 0xb0, 0x22, 0x3a, 0x82, 0xad, 0x90, 0xa7, 0x79, 0x91, 0x64, 0xea,
	0xd2, 0xf4, 0xe8, 0xad, 0xd1, 0xbb, 0x95, 0xa3, 0x5a, 0x65, 0xfb, 0xb0, 0x8c, 0xb5, 0xa7, 0x53,
	0x85, 0x5b, 0x2e, 0x7e, 0x02, 0xf0, 0xf6, 0x84, 0x4a, 0xc9, 0xd2, 0xe9, 0xb3, 0x19, 0x15, 0x82,
	0x45, 0x14, 0x75, 0xec, 0xc2, 0x81, 0x5e, 0xb8, 0x81, 0x9a, 0xad, 0xed, 0xc3, 0xcd, 0x19, 0x89,
	0x8b, 0xab, 0x5b, 0x30, 0x2e, 0x63, 0x42, 0xef, 0x40, 0xa8, 0x05, 0x5f, 0xbe, 0xcc, 0xae, 0x5e,
	0xbc, 0x09, 0x68, 0x6a, 0xfb, 0x8b, 0x97, 0x19, 0x45, 0x7b, 0xf0, 0x2d, 0x41, 0x49, 0x6e, 0xbb,
	0x6f, 0x62, 0xab, 0xd9, 0x66, 0x7e, 0xab, 0xc3, 0x5d, 0xd3, 0xbb, 0xda, 0xcc, 0x97, 0x4c, 0x9e,
	0xea, 0x35, 0xa1, 0xc7, 0xb0, 0xa1, 0x7e, 0x9d, 0x75, 0x43, 0xad, 0x51, 0xff, 0xbf, 0x7e, 0xad,
	0xdc, 0x9b, 0xaa, 0xec, 0xc5, 0xbc, 0x07, 0xb0, 0xc6, 0xa1, 0xfb, 0x70, 0xb3, 0x50, 0x89, 0x74,
	0xdb, 0xd7, 0x27, 0x58, 0xde, 0x04, 0x36, 0xe1, 0xe8, 0x29, 0xdc, 0xa2, 0x3f, 0x48, 0x41, 0xfc,
	0x90, 0xc7, 0x45, 0x92, 0xe6, 0x7a, 0xaa, 0xd6, 0xa8, 0x7b, 0x0d, 0xde, 0x3e, 0xa6, 0x4a, 0xf9,
	0xb6, 0x86, 0x1f, 0x1a, 0x34, 0x9a, 0xc0, 0x9d, 0xdc, 0x50, 0xed, 0x73, 0xcb, 0x75, 0xde, 0x69,
	0xf4, 0x37, 0x06, 0xad, 0xd1, 0x7b, 0xd7, 0xa5, 0x5c, 0x5d, 0x0d, 0xde, 0xce, 0x57, 0x0d, 0xb9,
	0x61, 0xce, 0xfd, 0xe6, 0xfc, 0xcf, 0x6e, 0xed, 0x7c, 0xd1, 0x05, 0x17, 0x8b, 0x2e, 0x78, 0xb5,
	0xe8, 0x82, 0x3f, 0x16, 0x5d, 0xf0, 0xf3, 0x65, 0xb7, 0x76, 0x71, 0xd9, 0xad, 0xbd, 0xba, 0xec,
	0xd6, 0xbe, 0x7e, 0xf0, 0x46, 0xef, 0x75, 0xdd, 0x3f, 0xe3, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff,
	0x08, 0x0d, 0xc9, 0xd3, 0x30, 0x07, 0x00, 0x00,
}

func (this *ProtoInfo) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*ProtoInfo)
	if !ok {
		that2, ok := that.(ProtoInfo)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.DeprecatedID != that1.DeprecatedID {
		return false
	}
	if this.DeprecatedDataState != that1.DeprecatedDataState {
		return false
	}
	if this.DroppedName != that1.DroppedName {
		return false
	}
	if this.TenantReplicationJobID != that1.TenantReplicationJobID {
		return false
	}
	if !this.Capabilities.Equal(&that1.Capabilities) {
		return false
	}
	return true
}
func (this *SQLInfo) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*SQLInfo)
	if !ok {
		that2, ok := that.(SQLInfo)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.ID != that1.ID {
		return false
	}
	if this.Name != that1.Name {
		return false
	}
	if this.DataState != that1.DataState {
		return false
	}
	if this.ServiceMode != that1.ServiceMode {
		return false
	}
	return true
}
func (this *UsageInfo) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*UsageInfo)
	if !ok {
		that2, ok := that.(UsageInfo)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.RUBurstLimit != that1.RUBurstLimit {
		return false
	}
	if this.RURefillRate != that1.RURefillRate {
		return false
	}
	if this.RUCurrent != that1.RUCurrent {
		return false
	}
	if !this.Consumption.Equal(&that1.Consumption) {
		return false
	}
	return true
}
func (this *SettingOverride) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*SettingOverride)
	if !ok {
		that2, ok := that.(SettingOverride)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Name != that1.Name {
		return false
	}
	if this.Value != that1.Value {
		return false
	}
	if this.ValueType != that1.ValueType {
		return false
	}
	if this.Reason != nil && that1.Reason != nil {
		if *this.Reason != *that1.Reason {
			return false
		}
	} else if this.Reason != nil {
		return false
	} else if that1.Reason != nil {
		return false
	}
	return true
}
func (this *TenantInfoWithUsage) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*TenantInfoWithUsage)
	if !ok {
		that2, ok := that.(TenantInfoWithUsage)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.ProtoInfo.Equal(&that1.ProtoInfo) {
		return false
	}
	if !this.Usage.Equal(that1.Usage) {
		return false
	}
	if !this.SQLInfo.Equal(&that1.SQLInfo) {
		return false
	}
	if len(this.SettingOverrides) != len(that1.SettingOverrides) {
		return false
	}
	for i := range this.SettingOverrides {
		if !this.SettingOverrides[i].Equal(that1.SettingOverrides[i]) {
			return false
		}
	}
	return true
}
func (m *ProtoInfo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ProtoInfo) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ProtoInfo) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Capabilities.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintInfo(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	i = encodeVarintInfo(dAtA, i, uint64(m.TenantReplicationJobID))
	i--
	dAtA[i] = 0x20
	i -= len(m.DroppedName)
	copy(dAtA[i:], m.DroppedName)
	i = encodeVarintInfo(dAtA, i, uint64(len(m.DroppedName)))
	i--
	dAtA[i] = 0x1a
	i = encodeVarintInfo(dAtA, i, uint64(m.DeprecatedDataState))
	i--
	dAtA[i] = 0x10
	i = encodeVarintInfo(dAtA, i, uint64(m.DeprecatedID))
	i--
	dAtA[i] = 0x8
	return len(dAtA) - i, nil
}

func (m *SQLInfo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SQLInfo) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SQLInfo) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	i = encodeVarintInfo(dAtA, i, uint64(m.ServiceMode))
	i--
	dAtA[i] = 0x20
	i = encodeVarintInfo(dAtA, i, uint64(m.DataState))
	i--
	dAtA[i] = 0x18
	i -= len(m.Name)
	copy(dAtA[i:], m.Name)
	i = encodeVarintInfo(dAtA, i, uint64(len(m.Name)))
	i--
	dAtA[i] = 0x12
	i = encodeVarintInfo(dAtA, i, uint64(m.ID))
	i--
	dAtA[i] = 0x8
	return len(dAtA) - i, nil
}

func (m *UsageInfo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *UsageInfo) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *UsageInfo) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Consumption.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintInfo(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	i -= 8
	encoding_binary.LittleEndian.PutUint64(dAtA[i:], uint64(math.Float64bits(float64(m.RUCurrent))))
	i--
	dAtA[i] = 0x19
	i -= 8
	encoding_binary.LittleEndian.PutUint64(dAtA[i:], uint64(math.Float64bits(float64(m.RURefillRate))))
	i--
	dAtA[i] = 0x11
	i -= 8
	encoding_binary.LittleEndian.PutUint64(dAtA[i:], uint64(math.Float64bits(float64(m.RUBurstLimit))))
	i--
	dAtA[i] = 0x9
	return len(dAtA) - i, nil
}

func (m *SettingOverride) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SettingOverride) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SettingOverride) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Reason != nil {
		i -= len(*m.Reason)
		copy(dAtA[i:], *m.Reason)
		i = encodeVarintInfo(dAtA, i, uint64(len(*m.Reason)))
		i--
		dAtA[i] = 0x22
	}
	i -= len(m.ValueType)
	copy(dAtA[i:], m.ValueType)
	i = encodeVarintInfo(dAtA, i, uint64(len(m.ValueType)))
	i--
	dAtA[i] = 0x1a
	i -= len(m.Value)
	copy(dAtA[i:], m.Value)
	i = encodeVarintInfo(dAtA, i, uint64(len(m.Value)))
	i--
	dAtA[i] = 0x12
	i -= len(m.Name)
	copy(dAtA[i:], m.Name)
	i = encodeVarintInfo(dAtA, i, uint64(len(m.Name)))
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *TenantInfoWithUsage) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *TenantInfoWithUsage) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *TenantInfoWithUsage) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.SettingOverrides) > 0 {
		for iNdEx := len(m.SettingOverrides) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.SettingOverrides[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintInfo(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	{
		size, err := m.SQLInfo.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintInfo(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if m.Usage != nil {
		{
			size, err := m.Usage.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintInfo(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	{
		size, err := m.ProtoInfo.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintInfo(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintInfo(dAtA []byte, offset int, v uint64) int {
	offset -= sovInfo(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *ProtoInfo) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	n += 1 + sovInfo(uint64(m.DeprecatedID))
	n += 1 + sovInfo(uint64(m.DeprecatedDataState))
	l = len(m.DroppedName)
	n += 1 + l + sovInfo(uint64(l))
	n += 1 + sovInfo(uint64(m.TenantReplicationJobID))
	l = m.Capabilities.Size()
	n += 1 + l + sovInfo(uint64(l))
	return n
}

func (m *SQLInfo) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	n += 1 + sovInfo(uint64(m.ID))
	l = len(m.Name)
	n += 1 + l + sovInfo(uint64(l))
	n += 1 + sovInfo(uint64(m.DataState))
	n += 1 + sovInfo(uint64(m.ServiceMode))
	return n
}

func (m *UsageInfo) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	n += 9
	n += 9
	n += 9
	l = m.Consumption.Size()
	n += 1 + l + sovInfo(uint64(l))
	return n
}

func (m *SettingOverride) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Name)
	n += 1 + l + sovInfo(uint64(l))
	l = len(m.Value)
	n += 1 + l + sovInfo(uint64(l))
	l = len(m.ValueType)
	n += 1 + l + sovInfo(uint64(l))
	if m.Reason != nil {
		l = len(*m.Reason)
		n += 1 + l + sovInfo(uint64(l))
	}
	return n
}

func (m *TenantInfoWithUsage) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.ProtoInfo.Size()
	n += 1 + l + sovInfo(uint64(l))
	if m.Usage != nil {
		l = m.Usage.Size()
		n += 1 + l + sovInfo(uint64(l))
	}
	l = m.SQLInfo.Size()
	n += 1 + l + sovInfo(uint64(l))
	if len(m.SettingOverrides) > 0 {
		for _, e := range m.SettingOverrides {
			l = e.Size()
			n += 1 + l + sovInfo(uint64(l))
		}
	}
	return n
}

func sovInfo(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozInfo(x uint64) (n int) {
	return sovInfo(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *ProtoInfo) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowInfo
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ProtoInfo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ProtoInfo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DeprecatedID", wireType)
			}
			m.DeprecatedID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DeprecatedID |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DeprecatedDataState", wireType)
			}
			m.DeprecatedDataState = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DeprecatedDataState |= ProtoInfo_DeprecatedDataState(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DroppedName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthInfo
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthInfo
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DroppedName = github_com_cockroachdb_cockroach_pkg_roachpb.TenantName(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TenantReplicationJobID", wireType)
			}
			m.TenantReplicationJobID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TenantReplicationJobID |= github_com_cockroachdb_cockroach_pkg_sql_catalog_catpb.JobID(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Capabilities", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthInfo
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthInfo
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Capabilities.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipInfo(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthInfo
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SQLInfo) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowInfo
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SQLInfo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SQLInfo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ID", wireType)
			}
			m.ID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ID |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthInfo
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthInfo
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = github_com_cockroachdb_cockroach_pkg_roachpb.TenantName(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DataState", wireType)
			}
			m.DataState = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DataState |= TenantDataState(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ServiceMode", wireType)
			}
			m.ServiceMode = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ServiceMode |= TenantServiceMode(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipInfo(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthInfo
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *UsageInfo) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowInfo
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: UsageInfo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: UsageInfo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 1 {
				return fmt.Errorf("proto: wrong wireType = %d for field RUBurstLimit", wireType)
			}
			var v uint64
			if (iNdEx + 8) > l {
				return io.ErrUnexpectedEOF
			}
			v = uint64(encoding_binary.LittleEndian.Uint64(dAtA[iNdEx:]))
			iNdEx += 8
			m.RUBurstLimit = float64(math.Float64frombits(v))
		case 2:
			if wireType != 1 {
				return fmt.Errorf("proto: wrong wireType = %d for field RURefillRate", wireType)
			}
			var v uint64
			if (iNdEx + 8) > l {
				return io.ErrUnexpectedEOF
			}
			v = uint64(encoding_binary.LittleEndian.Uint64(dAtA[iNdEx:]))
			iNdEx += 8
			m.RURefillRate = float64(math.Float64frombits(v))
		case 3:
			if wireType != 1 {
				return fmt.Errorf("proto: wrong wireType = %d for field RUCurrent", wireType)
			}
			var v uint64
			if (iNdEx + 8) > l {
				return io.ErrUnexpectedEOF
			}
			v = uint64(encoding_binary.LittleEndian.Uint64(dAtA[iNdEx:]))
			iNdEx += 8
			m.RUCurrent = float64(math.Float64frombits(v))
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Consumption", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthInfo
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthInfo
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Consumption.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipInfo(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthInfo
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SettingOverride) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowInfo
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SettingOverride: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SettingOverride: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthInfo
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthInfo
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Value", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthInfo
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthInfo
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Value = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValueType", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthInfo
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthInfo
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ValueType = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Reason", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthInfo
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthInfo
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.Reason = &s
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipInfo(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthInfo
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *TenantInfoWithUsage) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowInfo
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: TenantInfoWithUsage: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: TenantInfoWithUsage: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProtoInfo", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthInfo
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthInfo
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ProtoInfo.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Usage", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthInfo
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthInfo
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Usage == nil {
				m.Usage = &UsageInfo{}
			}
			if err := m.Usage.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SQLInfo", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthInfo
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthInfo
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.SQLInfo.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SettingOverrides", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthInfo
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthInfo
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SettingOverrides = append(m.SettingOverrides, &SettingOverride{})
			if err := m.SettingOverrides[len(m.SettingOverrides)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipInfo(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthInfo
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipInfo(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowInfo
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowInfo
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowInfo
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthInfo
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupInfo
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthInfo
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthInfo        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowInfo          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupInfo = fmt.Errorf("proto: unexpected end of group")
)
