node {
  name = "emqx@127.0.0.1"
  cookie = "r1db-isolated-test-cookie"
  data_dir = "data"
}

cluster {
  discovery_strategy = manual
}

listeners.tcp.default {
  bind = "0.0.0.0:1883"
  enable_authn = true
}

authentication = [
  {
    mechanism = password_based
    backend = built_in_database
    user_id_type = username
    password_hash_algorithm {
      name = sha256
      salt_position = suffix
    }
    bootstrap_file = "/opt/emqx/etc/auth-built-in-db-bootstrap.csv"
    bootstrap_type = plain
  }
]
