// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: sql/execinfrapb/processors_ttl.proto

// Beware! This package name must not be changed, even though it doesn't match
// the Go package name, because it defines the Protobuf message names which
// can't be changed without breaking backward compatibility.

package execinfrapb

import (
	fmt "fmt"
	github_com_cockroachdb_cockroach_pkg_jobs_jobspb "github.com/cockroachdb/cockroach/pkg/jobs/jobspb"
	jobspb "github.com/cockroachdb/cockroach/pkg/jobs/jobspb"
	roachpb "github.com/cockroachdb/cockroach/pkg/roachpb"
	github_com_cockroachdb_cockroach_pkg_sql_catalog_catpb "github.com/cockroachdb/cockroach/pkg/sql/catalog/catpb"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	_ "github.com/gogo/protobuf/types"
	github_com_gogo_protobuf_types "github.com/gogo/protobuf/types"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type TTLSpec struct {
	// JobID of the job that ran the ttlProcessor.
	JobID github_com_cockroachdb_cockroach_pkg_jobs_jobspb.JobID `protobuf:"varint,1,opt,name=job_id,json=jobId,casttype=github.com/cockroachdb/cockroach/pkg/jobs/jobspb.JobID" json:"job_id"`
	// RowLevelTTLDetails are the details of the job that ran the ttlProcessor.
	RowLevelTTLDetails jobspb.RowLevelTTLDetails `protobuf:"bytes,2,opt,name=row_level_ttl_details,json=rowLevelTtlDetails" json:"row_level_ttl_details"`
	// Deprecated: AOST has been replaced with AOSTDuration.
	// TODO(ewall): remove in 24.1
	// AOST is the AS OF SYSTEM TIME value the ttlProcessor uses to select records.
	AOST time.Time `protobuf:"bytes,3,opt,name=aost,stdtime" json:"aost"`
	// TTLExpr is compared against jobspb.RowLevelTTLDetails.Cutoff by the
	// ttlProcessor to determine what records to delete. Records are deleted
	// if TTLExpr <= Cutoff.
	TTLExpr github_com_cockroachdb_cockroach_pkg_sql_catalog_catpb.Expression `protobuf:"bytes,4,opt,name=ttl_expr,json=ttlExpr,casttype=github.com/cockroachdb/cockroach/pkg/sql/catalog/catpb.Expression" json:"ttl_expr"`
	// Spans determine which records are processed by which nodes in the DistSQL
	// flow.
	Spans []roachpb.Span `protobuf:"bytes,5,rep,name=spans" json:"spans"`
	// SelectBatchSize controls the batch size for SELECTs.
	SelectBatchSize int64 `protobuf:"varint,7,opt,name=select_batch_size,json=selectBatchSize" json:"select_batch_size"`
	// DeleteBatchSize controls the batch size for DELETEs.
	DeleteBatchSize int64 `protobuf:"varint,8,opt,name=delete_batch_size,json=deleteBatchSize" json:"delete_batch_size"`
	// DeleteRateLimit controls how many records can be deleted per second.
	DeleteRateLimit int64 `protobuf:"varint,9,opt,name=delete_rate_limit,json=deleteRateLimit" json:"delete_rate_limit"`
	// LabelMetrics controls if metrics are labeled with the name of the table being TTLed.
	LabelMetrics bool `protobuf:"varint,10,opt,name=label_metrics,json=labelMetrics" json:"label_metrics"`
	// PreDeleteChangeTableVersion is a test flag to change the table
	// descriptor before a delete.
	PreDeleteChangeTableVersion bool `protobuf:"varint,11,opt,name=pre_delete_change_table_version,json=preDeleteChangeTableVersion" json:"pre_delete_change_table_version"`
	// PreSelectStatement is a test setting to run a SQL statement
	// before selecting records.
	PreSelectStatement string `protobuf:"bytes,12,opt,name=pre_select_statement,json=preSelectStatement" json:"pre_select_statement"`
	// AOSTDuration is subtracted from the current time to determine the
	// AS OF SYSTEM TIME value the ttlProcessor uses to select records.
	AOSTDuration time.Duration `protobuf:"bytes,13,opt,name=aost_duration,json=aostDuration,stdduration" json:"aost_duration"`
}

func (m *TTLSpec) Reset()         { *m = TTLSpec{} }
func (m *TTLSpec) String() string { return proto.CompactTextString(m) }
func (*TTLSpec) ProtoMessage()    {}
func (*TTLSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_9edaf16d88891b65, []int{0}
}
func (m *TTLSpec) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *TTLSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *TTLSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TTLSpec.Merge(m, src)
}
func (m *TTLSpec) XXX_Size() int {
	return m.Size()
}
func (m *TTLSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_TTLSpec.DiscardUnknown(m)
}

var xxx_messageInfo_TTLSpec proto.InternalMessageInfo

func init() {
	proto.RegisterType((*TTLSpec)(nil), "cockroach.sql.distsqlrun.TTLSpec")
}

func init() {
	proto.RegisterFile("sql/execinfrapb/processors_ttl.proto", fileDescriptor_9edaf16d88891b65)
}

var fileDescriptor_9edaf16d88891b65 = []byte{
	// 663 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0x41, 0x6f, 0xd3, 0x4a,
	0x10, 0x8e, 0x5f, 0x93, 0x26, 0x75, 0x53, 0xbd, 0xbe, 0x55, 0x1f, 0x98, 0x20, 0x39, 0x11, 0xe2,
	0x10, 0x0e, 0xd8, 0xa8, 0xa0, 0x9e, 0xa9, 0x09, 0x42, 0xad, 0x82, 0x90, 0x12, 0xab, 0x42, 0x1c,
	0xb0, 0xd6, 0xf6, 0xd4, 0x71, 0xbb, 0xf1, 0x6e, 0x77, 0x37, 0x6d, 0x55, 0xf1, 0x23, 0x7a, 0xe4,
	0x27, 0xf5, 0xd8, 0x63, 0x4f, 0x01, 0xd2, 0xbf, 0xc0, 0xa9, 0x27, 0xb4, 0xeb, 0x0d, 0x04, 0xca,
	0xa1, 0x97, 0xec, 0xee, 0x7c, 0xdf, 0x37, 0x33, 0xf9, 0x66, 0x12, 0xfb, 0xb1, 0x38, 0x22, 0x3e,
	0x9c, 0x42, 0x92, 0x17, 0xfb, 0x1c, 0xb3, 0xd8, 0x67, 0x9c, 0x26, 0x20, 0x04, 0xe5, 0x22, 0x92,
	0x92, 0x78, 0x8c, 0x53, 0x49, 0x91, 0x93, 0xd0, 0xe4, 0x90, 0x53, 0x9c, 0x8c, 0x3c, 0x71, 0x44,
	0xbc, 0x34, 0x17, 0x52, 0x1c, 0x11, 0x3e, 0x29, 0x5a, 0x1b, 0x19, 0xcd, 0xa8, 0x26, 0xf9, 0xea,
	0x56, 0xf2, 0x5b, 0x6e, 0x46, 0x69, 0x46, 0xc0, 0xd7, 0xaf, 0x78, 0xb2, 0xef, 0xa7, 0x13, 0x8e,
	0x65, 0x4e, 0x0b, 0x83, 0xb7, 0xff, 0xc4, 0x65, 0x3e, 0x06, 0x21, 0xf1, 0x98, 0x19, 0x02, 0xd2,
	0xc5, 0x58, 0xec, 0xa7, 0x58, 0x62, 0x13, 0xbb, 0x77, 0x40, 0x63, 0xe1, 0xab, 0x0f, 0x16, 0xeb,
	0xa3, 0x8c, 0x3f, 0xfa, 0xbe, 0x6c, 0xd7, 0xc3, 0xb0, 0x3f, 0x64, 0x90, 0xa0, 0x8f, 0xf6, 0xf2,
	0x01, 0x8d, 0xa3, 0x3c, 0x75, 0xac, 0x8e, 0xd5, 0x5d, 0x0a, 0xde, 0x5c, 0x4c, 0xdb, 0x95, 0xd9,
	0xb4, 0x5d, 0xdb, 0xa5, 0xf1, 0x4e, 0xef, 0x66, 0xda, 0xde, 0xca, 0x72, 0x39, 0x9a, 0xc4, 0x5e,
	0x42, 0xc7, 0xfe, 0xcf, 0x2f, 0x95, 0xc6, 0xbf, 0xee, 0x3e, 0x3b, 0xcc, 0xfc, 0x85, 0x4a, 0x9e,
	0x56, 0x0e, 0x6a, 0x07, 0x34, 0xde, 0x49, 0xd1, 0x27, 0xfb, 0x7f, 0x4e, 0x4f, 0x22, 0x02, 0xc7,
	0x40, 0x94, 0x3f, 0x51, 0x0a, 0x12, 0xe7, 0x44, 0x38, 0xff, 0x74, 0xac, 0xee, 0xea, 0xe6, 0x53,
	0xef, 0x77, 0xa3, 0x74, 0x97, 0x26, 0xcf, 0x80, 0x9e, 0xf4, 0x95, 0x2c, 0x0c, 0xfb, 0xbd, 0x52,
	0x14, 0xb4, 0x4c, 0x77, 0xe8, 0x36, 0x36, 0x40, 0x7c, 0x1e, 0x93, 0xc4, 0xc4, 0xd0, 0x4b, 0xbb,
	0x8a, 0xa9, 0x90, 0xce, 0x92, 0x2e, 0xd6, 0xf2, 0x4a, 0x17, 0xbd, 0xb9, 0x8b, 0x5e, 0x38, 0x77,
	0x31, 0x58, 0x37, 0x99, 0xab, 0xdb, 0xef, 0x86, 0xe1, 0xf9, 0x97, 0xb6, 0x35, 0xd0, 0x4a, 0x44,
	0xed, 0x86, 0xea, 0x1a, 0x4e, 0x19, 0x77, 0xaa, 0x1d, 0xab, 0xbb, 0x12, 0x84, 0x86, 0xa9, 0x2c,
	0x7c, 0x7d, 0xca, 0xf8, 0xcd, 0xb4, 0xbd, 0x7d, 0x27, 0x8f, 0xd4, 0xe2, 0x24, 0x58, 0x62, 0x42,
	0x33, 0x75, 0xb2, 0xd8, 0x53, 0x72, 0x10, 0x22, 0xa7, 0xc5, 0xa0, 0x2e, 0x25, 0x51, 0x4f, 0xf4,
	0xdc, 0xae, 0x09, 0x86, 0x0b, 0xe1, 0xd4, 0x3a, 0x4b, 0xdd, 0xd5, 0xcd, 0xfb, 0x0b, 0x06, 0x99,
	0x11, 0x7b, 0x43, 0x86, 0x8b, 0xa0, 0xaa, 0xda, 0x18, 0x94, 0x5c, 0xf4, 0xcc, 0xfe, 0x4f, 0x00,
	0x81, 0x44, 0x46, 0x31, 0x96, 0xc9, 0x28, 0x12, 0xf9, 0x19, 0x38, 0x75, 0x3d, 0xd0, 0x92, 0xf7,
	0x6f, 0x09, 0x07, 0x0a, 0x1d, 0xe6, 0x67, 0xa0, 0x14, 0x29, 0x10, 0x90, 0xb0, 0xa8, 0x68, 0x2c,
	0x2a, 0x4a, 0xf8, 0x6f, 0x0a, 0x8e, 0x25, 0x44, 0x24, 0x1f, 0xe7, 0xd2, 0x59, 0xb9, 0xad, 0x18,
	0x60, 0x09, 0x7d, 0x05, 0xa2, 0x27, 0xf6, 0x1a, 0xc1, 0x31, 0x90, 0x68, 0x0c, 0x92, 0xe7, 0x89,
	0x70, 0xec, 0x8e, 0xd5, 0x6d, 0x18, 0x76, 0x53, 0x43, 0x6f, 0x4b, 0x04, 0xed, 0xda, 0x6d, 0xc6,
	0x21, 0x32, 0x05, 0x92, 0x11, 0x2e, 0x32, 0x88, 0x24, 0x8e, 0x09, 0x44, 0xc7, 0xc0, 0x95, 0x43,
	0xce, 0xea, 0x82, 0xf8, 0x21, 0xe3, 0xd0, 0xd3, 0xdc, 0x57, 0x9a, 0x1a, 0x2a, 0xe6, 0x5e, 0x49,
	0x44, 0x5b, 0xf6, 0x86, 0xca, 0x65, 0x0c, 0x11, 0x12, 0x4b, 0x18, 0x43, 0x21, 0x9d, 0xa6, 0x1e,
	0x5f, 0x99, 0x00, 0x31, 0x0e, 0x43, 0x4d, 0x18, 0xce, 0x71, 0xf4, 0xde, 0x5e, 0x53, 0x23, 0x8f,
	0xe6, 0x3f, 0x3d, 0x67, 0x4d, 0x6f, 0xcd, 0x83, 0x5b, 0x5b, 0xd3, 0x33, 0x84, 0xc0, 0x31, 0xab,
	0xd0, 0x54, 0x4b, 0x33, 0x8f, 0x7e, 0x56, 0xcb, 0xd3, 0x54, 0x99, 0xe6, 0x91, 0xdd, 0x6a, 0x63,
	0x79, 0xbd, 0x1e, 0xec, 0x5d, 0x7c, 0x73, 0x2b, 0x17, 0x33, 0xd7, 0xba, 0x9c, 0xb9, 0xd6, 0xd5,
	0xcc, 0xb5, 0xbe, 0xce, 0x5c, 0xeb, 0xfc, 0xda, 0xad, 0x5c, 0x5e, 0xbb, 0x95, 0xab, 0x6b, 0xb7,
	0xf2, 0xe1, 0xc5, 0x9d, 0xf7, 0x68, 0xe1, 0x0f, 0xe8, 0x47, 0x00, 0x00, 0x00, 0xff, 0xff, 0x08,
	0x93, 0xbd, 0x96, 0x92, 0x04, 0x00, 0x00,
}

func (m *TTLSpec) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *TTLSpec) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *TTLSpec) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	n1, err1 := github_com_gogo_protobuf_types.StdDurationMarshalTo(m.AOSTDuration, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdDuration(m.AOSTDuration):])
	if err1 != nil {
		return 0, err1
	}
	i -= n1
	i = encodeVarintProcessorsTtl(dAtA, i, uint64(n1))
	i--
	dAtA[i] = 0x6a
	i -= len(m.PreSelectStatement)
	copy(dAtA[i:], m.PreSelectStatement)
	i = encodeVarintProcessorsTtl(dAtA, i, uint64(len(m.PreSelectStatement)))
	i--
	dAtA[i] = 0x62
	i--
	if m.PreDeleteChangeTableVersion {
		dAtA[i] = 1
	} else {
		dAtA[i] = 0
	}
	i--
	dAtA[i] = 0x58
	i--
	if m.LabelMetrics {
		dAtA[i] = 1
	} else {
		dAtA[i] = 0
	}
	i--
	dAtA[i] = 0x50
	i = encodeVarintProcessorsTtl(dAtA, i, uint64(m.DeleteRateLimit))
	i--
	dAtA[i] = 0x48
	i = encodeVarintProcessorsTtl(dAtA, i, uint64(m.DeleteBatchSize))
	i--
	dAtA[i] = 0x40
	i = encodeVarintProcessorsTtl(dAtA, i, uint64(m.SelectBatchSize))
	i--
	dAtA[i] = 0x38
	if len(m.Spans) > 0 {
		for iNdEx := len(m.Spans) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Spans[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintProcessorsTtl(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x2a
		}
	}
	i -= len(m.TTLExpr)
	copy(dAtA[i:], m.TTLExpr)
	i = encodeVarintProcessorsTtl(dAtA, i, uint64(len(m.TTLExpr)))
	i--
	dAtA[i] = 0x22
	n2, err2 := github_com_gogo_protobuf_types.StdTimeMarshalTo(m.AOST, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdTime(m.AOST):])
	if err2 != nil {
		return 0, err2
	}
	i -= n2
	i = encodeVarintProcessorsTtl(dAtA, i, uint64(n2))
	i--
	dAtA[i] = 0x1a
	{
		size, err := m.RowLevelTTLDetails.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintProcessorsTtl(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	i = encodeVarintProcessorsTtl(dAtA, i, uint64(m.JobID))
	i--
	dAtA[i] = 0x8
	return len(dAtA) - i, nil
}

func encodeVarintProcessorsTtl(dAtA []byte, offset int, v uint64) int {
	offset -= sovProcessorsTtl(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *TTLSpec) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	n += 1 + sovProcessorsTtl(uint64(m.JobID))
	l = m.RowLevelTTLDetails.Size()
	n += 1 + l + sovProcessorsTtl(uint64(l))
	l = github_com_gogo_protobuf_types.SizeOfStdTime(m.AOST)
	n += 1 + l + sovProcessorsTtl(uint64(l))
	l = len(m.TTLExpr)
	n += 1 + l + sovProcessorsTtl(uint64(l))
	if len(m.Spans) > 0 {
		for _, e := range m.Spans {
			l = e.Size()
			n += 1 + l + sovProcessorsTtl(uint64(l))
		}
	}
	n += 1 + sovProcessorsTtl(uint64(m.SelectBatchSize))
	n += 1 + sovProcessorsTtl(uint64(m.DeleteBatchSize))
	n += 1 + sovProcessorsTtl(uint64(m.DeleteRateLimit))
	n += 2
	n += 2
	l = len(m.PreSelectStatement)
	n += 1 + l + sovProcessorsTtl(uint64(l))
	l = github_com_gogo_protobuf_types.SizeOfStdDuration(m.AOSTDuration)
	n += 1 + l + sovProcessorsTtl(uint64(l))
	return n
}

func sovProcessorsTtl(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozProcessorsTtl(x uint64) (n int) {
	return sovProcessorsTtl(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *TTLSpec) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowProcessorsTtl
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: TTLSpec: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: TTLSpec: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field JobID", wireType)
			}
			m.JobID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProcessorsTtl
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.JobID |= github_com_cockroachdb_cockroach_pkg_jobs_jobspb.JobID(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RowLevelTTLDetails", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProcessorsTtl
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthProcessorsTtl
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthProcessorsTtl
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.RowLevelTTLDetails.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AOST", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProcessorsTtl
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthProcessorsTtl
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthProcessorsTtl
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_gogo_protobuf_types.StdTimeUnmarshal(&m.AOST, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TTLExpr", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProcessorsTtl
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthProcessorsTtl
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthProcessorsTtl
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TTLExpr = github_com_cockroachdb_cockroach_pkg_sql_catalog_catpb.Expression(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Spans", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProcessorsTtl
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthProcessorsTtl
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthProcessorsTtl
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Spans = append(m.Spans, roachpb.Span{})
			if err := m.Spans[len(m.Spans)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SelectBatchSize", wireType)
			}
			m.SelectBatchSize = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProcessorsTtl
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SelectBatchSize |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DeleteBatchSize", wireType)
			}
			m.DeleteBatchSize = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProcessorsTtl
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DeleteBatchSize |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DeleteRateLimit", wireType)
			}
			m.DeleteRateLimit = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProcessorsTtl
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DeleteRateLimit |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LabelMetrics", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProcessorsTtl
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.LabelMetrics = bool(v != 0)
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PreDeleteChangeTableVersion", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProcessorsTtl
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.PreDeleteChangeTableVersion = bool(v != 0)
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PreSelectStatement", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProcessorsTtl
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthProcessorsTtl
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthProcessorsTtl
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PreSelectStatement = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 13:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AOSTDuration", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProcessorsTtl
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthProcessorsTtl
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthProcessorsTtl
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_gogo_protobuf_types.StdDurationUnmarshal(&m.AOSTDuration, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipProcessorsTtl(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthProcessorsTtl
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipProcessorsTtl(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowProcessorsTtl
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowProcessorsTtl
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowProcessorsTtl
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthProcessorsTtl
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupProcessorsTtl
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthProcessorsTtl
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthProcessorsTtl        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowProcessorsTtl          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupProcessorsTtl = fmt.Errorf("proto: unexpected end of group")
)
