// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: util/log/eventpb/cluster_events.proto

package eventpb

import (
	fmt "fmt"
	logpb "github.com/cockroachdb/cockroach/pkg/util/log/logpb"
	github_com_cockroachdb_redact "github.com/cockroachdb/redact"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// CommonNodeEventDetails contains the fields common to all
// node-level events.
type CommonNodeEventDetails struct {
	// The node ID where the event was originated.
	NodeID int32 `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:",omitempty"`
	// The time when this node was last started.
	StartedAt int64 `protobuf:"varint,3,opt,name=started_at,json=startedAt,proto3" json:",omitempty"`
	// The approximate last time the node was up before the last restart.
	LastUp int64 `protobuf:"varint,4,opt,name=last_up,json=lastUp,proto3" json:",omitempty"`
}

func (m *CommonNodeEventDetails) Reset()         { *m = CommonNodeEventDetails{} }
func (m *CommonNodeEventDetails) String() string { return proto.CompactTextString(m) }
func (*CommonNodeEventDetails) ProtoMessage()    {}
func (*CommonNodeEventDetails) Descriptor() ([]byte, []int) {
	return fileDescriptor_7419df72f0fda340, []int{0}
}
func (m *CommonNodeEventDetails) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CommonNodeEventDetails) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *CommonNodeEventDetails) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommonNodeEventDetails.Merge(m, src)
}
func (m *CommonNodeEventDetails) XXX_Size() int {
	return m.Size()
}
func (m *CommonNodeEventDetails) XXX_DiscardUnknown() {
	xxx_messageInfo_CommonNodeEventDetails.DiscardUnknown(m)
}

var xxx_messageInfo_CommonNodeEventDetails proto.InternalMessageInfo

// NodeJoin is recorded when a node joins the cluster.
type NodeJoin struct {
	logpb.CommonEventDetails `protobuf:"bytes,1,opt,name=common,proto3,embedded=common" json:""`
	CommonNodeEventDetails   `protobuf:"bytes,2,opt,name=node,proto3,embedded=node" json:""`
}

func (m *NodeJoin) Reset()         { *m = NodeJoin{} }
func (m *NodeJoin) String() string { return proto.CompactTextString(m) }
func (*NodeJoin) ProtoMessage()    {}
func (*NodeJoin) Descriptor() ([]byte, []int) {
	return fileDescriptor_7419df72f0fda340, []int{1}
}
func (m *NodeJoin) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *NodeJoin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *NodeJoin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeJoin.Merge(m, src)
}
func (m *NodeJoin) XXX_Size() int {
	return m.Size()
}
func (m *NodeJoin) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeJoin.DiscardUnknown(m)
}

var xxx_messageInfo_NodeJoin proto.InternalMessageInfo

// NodeRestart is recorded when an existing node rejoins the cluster
// after being offline.
type NodeRestart struct {
	logpb.CommonEventDetails `protobuf:"bytes,1,opt,name=common,proto3,embedded=common" json:""`
	CommonNodeEventDetails   `protobuf:"bytes,2,opt,name=node,proto3,embedded=node" json:""`
}

func (m *NodeRestart) Reset()         { *m = NodeRestart{} }
func (m *NodeRestart) String() string { return proto.CompactTextString(m) }
func (*NodeRestart) ProtoMessage()    {}
func (*NodeRestart) Descriptor() ([]byte, []int) {
	return fileDescriptor_7419df72f0fda340, []int{2}
}
func (m *NodeRestart) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *NodeRestart) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *NodeRestart) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeRestart.Merge(m, src)
}
func (m *NodeRestart) XXX_Size() int {
	return m.Size()
}
func (m *NodeRestart) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeRestart.DiscardUnknown(m)
}

var xxx_messageInfo_NodeRestart proto.InternalMessageInfo

// NodeShutdownConnectionTimeout is recorded when SQL connections remain open
// during shutdown, after waiting for the server.shutdown.connections.timeout
// to transpire.
type NodeShutdownConnectionTimeout struct {
	logpb.CommonEventDetails `protobuf:"bytes,1,opt,name=common,proto3,embedded=common" json:""`
	CommonNodeEventDetails   `protobuf:"bytes,2,opt,name=node,proto3,embedded=node" json:""`
	// The detailed message, meant to be a human-understandable explanation.
	Detail github_com_cockroachdb_redact.SafeString `protobuf:"bytes,3,opt,name=detail,proto3,customtype=github.com/cockroachdb/redact.SafeString" json:",omitempty" redact:"nonsensitive"`
	// The number of connections still open after waiting for the client to close them.
	ConnectionsRemaining uint32 `protobuf:"varint,4,opt,name=connections_remaining,json=connectionsRemaining,proto3" json:",includeempty"`
	// The amount of time the server waited for the client to close the connections, defined by server.shutdown.connections.timeout.
	TimeoutMillis uint32 `protobuf:"varint,5,opt,name=timeout_millis,json=timeoutMillis,proto3" json:",includeempty"`
}

func (m *NodeShutdownConnectionTimeout) Reset()         { *m = NodeShutdownConnectionTimeout{} }
func (m *NodeShutdownConnectionTimeout) String() string { return proto.CompactTextString(m) }
func (*NodeShutdownConnectionTimeout) ProtoMessage()    {}
func (*NodeShutdownConnectionTimeout) Descriptor() ([]byte, []int) {
	return fileDescriptor_7419df72f0fda340, []int{3}
}
func (m *NodeShutdownConnectionTimeout) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *NodeShutdownConnectionTimeout) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *NodeShutdownConnectionTimeout) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeShutdownConnectionTimeout.Merge(m, src)
}
func (m *NodeShutdownConnectionTimeout) XXX_Size() int {
	return m.Size()
}
func (m *NodeShutdownConnectionTimeout) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeShutdownConnectionTimeout.DiscardUnknown(m)
}

var xxx_messageInfo_NodeShutdownConnectionTimeout proto.InternalMessageInfo

// NodeShutdownTransactionTimeout is recorded when SQL transactions remain open
// during shutdown, after waiting for the server.shutdown.transactions.timeout
// to transpire.
type NodeShutdownTransactionTimeout struct {
	logpb.CommonEventDetails `protobuf:"bytes,1,opt,name=common,proto3,embedded=common" json:""`
	CommonNodeEventDetails   `protobuf:"bytes,2,opt,name=node,proto3,embedded=node" json:""`
	// The detailed message, meant to be a human-understandable explanation.
	Detail github_com_cockroachdb_redact.SafeString `protobuf:"bytes,3,opt,name=detail,proto3,customtype=github.com/cockroachdb/redact.SafeString" json:",omitempty" redact:"nonsensitive"`
	// The number of connections still running SQL transactions after waiting for the client to end them.
	ConnectionsRemaining uint32 `protobuf:"varint,4,opt,name=connections_remaining,json=connectionsRemaining,proto3" json:",includeempty"`
	// The amount of time the server waited for the client to close the connections, defined by server.shutdown.transactions.timeout.
	TimeoutMillis uint32 `protobuf:"varint,5,opt,name=timeout_millis,json=timeoutMillis,proto3" json:",includeempty"`
}

func (m *NodeShutdownTransactionTimeout) Reset()         { *m = NodeShutdownTransactionTimeout{} }
func (m *NodeShutdownTransactionTimeout) String() string { return proto.CompactTextString(m) }
func (*NodeShutdownTransactionTimeout) ProtoMessage()    {}
func (*NodeShutdownTransactionTimeout) Descriptor() ([]byte, []int) {
	return fileDescriptor_7419df72f0fda340, []int{4}
}
func (m *NodeShutdownTransactionTimeout) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *NodeShutdownTransactionTimeout) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *NodeShutdownTransactionTimeout) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeShutdownTransactionTimeout.Merge(m, src)
}
func (m *NodeShutdownTransactionTimeout) XXX_Size() int {
	return m.Size()
}
func (m *NodeShutdownTransactionTimeout) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeShutdownTransactionTimeout.DiscardUnknown(m)
}

var xxx_messageInfo_NodeShutdownTransactionTimeout proto.InternalMessageInfo

// CommonNodeDecommissionDetails contains the fields common to all
// node-level decommission/recommission events.
//
// Notes to CockroachDB maintainers: refer to doc.go at the package
// level for more details. Beware that JSON compatibility rules apply
// here, not protobuf.
// *Really look at doc.go before modifying this.*
type CommonNodeDecommissionDetails struct {
	// The node ID where the event was originated.
	RequestingNodeID int32 `protobuf:"varint,1,opt,name=requesting_node_id,json=requestingNodeId,proto3" json:",omitempty"`
	// The node ID affected by the operation.
	TargetNodeID int32 `protobuf:"varint,2,opt,name=target_node_id,json=targetNodeId,proto3" json:",omitempty"`
}

func (m *CommonNodeDecommissionDetails) Reset()         { *m = CommonNodeDecommissionDetails{} }
func (m *CommonNodeDecommissionDetails) String() string { return proto.CompactTextString(m) }
func (*CommonNodeDecommissionDetails) ProtoMessage()    {}
func (*CommonNodeDecommissionDetails) Descriptor() ([]byte, []int) {
	return fileDescriptor_7419df72f0fda340, []int{5}
}
func (m *CommonNodeDecommissionDetails) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CommonNodeDecommissionDetails) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *CommonNodeDecommissionDetails) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommonNodeDecommissionDetails.Merge(m, src)
}
func (m *CommonNodeDecommissionDetails) XXX_Size() int {
	return m.Size()
}
func (m *CommonNodeDecommissionDetails) XXX_DiscardUnknown() {
	xxx_messageInfo_CommonNodeDecommissionDetails.DiscardUnknown(m)
}

var xxx_messageInfo_CommonNodeDecommissionDetails proto.InternalMessageInfo

// NodeDecommissioning is recorded when a node is marked as
// decommissioning.
type NodeDecommissioning struct {
	logpb.CommonEventDetails      `protobuf:"bytes,1,opt,name=common,proto3,embedded=common" json:""`
	CommonNodeDecommissionDetails `protobuf:"bytes,2,opt,name=node,proto3,embedded=node" json:""`
}

func (m *NodeDecommissioning) Reset()         { *m = NodeDecommissioning{} }
func (m *NodeDecommissioning) String() string { return proto.CompactTextString(m) }
func (*NodeDecommissioning) ProtoMessage()    {}
func (*NodeDecommissioning) Descriptor() ([]byte, []int) {
	return fileDescriptor_7419df72f0fda340, []int{6}
}
func (m *NodeDecommissioning) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *NodeDecommissioning) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *NodeDecommissioning) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeDecommissioning.Merge(m, src)
}
func (m *NodeDecommissioning) XXX_Size() int {
	return m.Size()
}
func (m *NodeDecommissioning) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeDecommissioning.DiscardUnknown(m)
}

var xxx_messageInfo_NodeDecommissioning proto.InternalMessageInfo

// NodeDecommissioned is recorded when a node is marked as
// decommissioned.
type NodeDecommissioned struct {
	logpb.CommonEventDetails      `protobuf:"bytes,1,opt,name=common,proto3,embedded=common" json:""`
	CommonNodeDecommissionDetails `protobuf:"bytes,2,opt,name=node,proto3,embedded=node" json:""`
}

func (m *NodeDecommissioned) Reset()         { *m = NodeDecommissioned{} }
func (m *NodeDecommissioned) String() string { return proto.CompactTextString(m) }
func (*NodeDecommissioned) ProtoMessage()    {}
func (*NodeDecommissioned) Descriptor() ([]byte, []int) {
	return fileDescriptor_7419df72f0fda340, []int{7}
}
func (m *NodeDecommissioned) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *NodeDecommissioned) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *NodeDecommissioned) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeDecommissioned.Merge(m, src)
}
func (m *NodeDecommissioned) XXX_Size() int {
	return m.Size()
}
func (m *NodeDecommissioned) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeDecommissioned.DiscardUnknown(m)
}

var xxx_messageInfo_NodeDecommissioned proto.InternalMessageInfo

// NodeRecommissioned is recorded when a decommissioning node is
// recommissioned.
type NodeRecommissioned struct {
	logpb.CommonEventDetails      `protobuf:"bytes,1,opt,name=common,proto3,embedded=common" json:""`
	CommonNodeDecommissionDetails `protobuf:"bytes,2,opt,name=node,proto3,embedded=node" json:""`
}

func (m *NodeRecommissioned) Reset()         { *m = NodeRecommissioned{} }
func (m *NodeRecommissioned) String() string { return proto.CompactTextString(m) }
func (*NodeRecommissioned) ProtoMessage()    {}
func (*NodeRecommissioned) Descriptor() ([]byte, []int) {
	return fileDescriptor_7419df72f0fda340, []int{8}
}
func (m *NodeRecommissioned) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *NodeRecommissioned) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *NodeRecommissioned) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeRecommissioned.Merge(m, src)
}
func (m *NodeRecommissioned) XXX_Size() int {
	return m.Size()
}
func (m *NodeRecommissioned) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeRecommissioned.DiscardUnknown(m)
}

var xxx_messageInfo_NodeRecommissioned proto.InternalMessageInfo

// CertsReload is recorded when the TLS certificates are
// reloaded/rotated from disk.
type CertsReload struct {
	logpb.CommonEventDetails `protobuf:"bytes,1,opt,name=common,proto3,embedded=common" json:""`
	// Whether the operation completed without errors.
	Success bool `protobuf:"varint,2,opt,name=success,proto3" json:",omitempty"`
	// If an error was encountered, the text of the error.
	ErrorMessage string `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:",omitempty"`
}

func (m *CertsReload) Reset()         { *m = CertsReload{} }
func (m *CertsReload) String() string { return proto.CompactTextString(m) }
func (*CertsReload) ProtoMessage()    {}
func (*CertsReload) Descriptor() ([]byte, []int) {
	return fileDescriptor_7419df72f0fda340, []int{9}
}
func (m *CertsReload) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CertsReload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *CertsReload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CertsReload.Merge(m, src)
}
func (m *CertsReload) XXX_Size() int {
	return m.Size()
}
func (m *CertsReload) XXX_DiscardUnknown() {
	xxx_messageInfo_CertsReload.DiscardUnknown(m)
}

var xxx_messageInfo_CertsReload proto.InternalMessageInfo

// CommonSharedServiceEventDetails contains the fields common to all
// tenant shared server events.
//
// Notes to CockroachDB maintainers: refer to doc.go at the package
// level for more details. Beware that JSON compatibility rules apply
// here, not protobuf.
// *Really look at doc.go before modifying this.*
type CommonSharedServiceEventDetails struct {
	// The node ID where the event was originated.
	NodeID int32 `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:",omitempty"`
	// The ID of the tenant owning the service.
	TenantID uint64 `protobuf:"varint,2,opt,name=tenant_id,json=tenantId,proto3" json:",omitempty"`
	// The ID of the server instance.
	InstanceID int32 `protobuf:"varint,3,opt,name=instance_id,json=instanceId,proto3" json:",omitempty"`
	// The name of the tenant at the time the event was emitted.
	TenantName string `protobuf:"bytes,4,opt,name=tenant_name,json=tenantName,proto3" json:",omitempty"`
}

func (m *CommonSharedServiceEventDetails) Reset()         { *m = CommonSharedServiceEventDetails{} }
func (m *CommonSharedServiceEventDetails) String() string { return proto.CompactTextString(m) }
func (*CommonSharedServiceEventDetails) ProtoMessage()    {}
func (*CommonSharedServiceEventDetails) Descriptor() ([]byte, []int) {
	return fileDescriptor_7419df72f0fda340, []int{10}
}
func (m *CommonSharedServiceEventDetails) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CommonSharedServiceEventDetails) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *CommonSharedServiceEventDetails) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommonSharedServiceEventDetails.Merge(m, src)
}
func (m *CommonSharedServiceEventDetails) XXX_Size() int {
	return m.Size()
}
func (m *CommonSharedServiceEventDetails) XXX_DiscardUnknown() {
	xxx_messageInfo_CommonSharedServiceEventDetails.DiscardUnknown(m)
}

var xxx_messageInfo_CommonSharedServiceEventDetails proto.InternalMessageInfo

// TenantSharedServiceStart is recorded when a tenant server
// is started inside the same process as the KV layer.
type TenantSharedServiceStart struct {
	logpb.CommonEventDetails        `protobuf:"bytes,1,opt,name=common,proto3,embedded=common" json:""`
	CommonSharedServiceEventDetails `protobuf:"bytes,2,opt,name=shared,proto3,embedded=shared" json:""`
	// Whether the startup was successful.
	OK bool `protobuf:"varint,3,opt,name=ok,proto3" json:",omitempty"`
	// If the startup failed, the text of the error.
	ErrorText github_com_cockroachdb_redact.RedactableString `protobuf:"bytes,4,opt,name=error_text,json=errorText,proto3,customtype=github.com/cockroachdb/redact.RedactableString" json:",omitempty" redact:"mixed"`
}

func (m *TenantSharedServiceStart) Reset()         { *m = TenantSharedServiceStart{} }
func (m *TenantSharedServiceStart) String() string { return proto.CompactTextString(m) }
func (*TenantSharedServiceStart) ProtoMessage()    {}
func (*TenantSharedServiceStart) Descriptor() ([]byte, []int) {
	return fileDescriptor_7419df72f0fda340, []int{11}
}
func (m *TenantSharedServiceStart) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *TenantSharedServiceStart) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *TenantSharedServiceStart) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TenantSharedServiceStart.Merge(m, src)
}
func (m *TenantSharedServiceStart) XXX_Size() int {
	return m.Size()
}
func (m *TenantSharedServiceStart) XXX_DiscardUnknown() {
	xxx_messageInfo_TenantSharedServiceStart.DiscardUnknown(m)
}

var xxx_messageInfo_TenantSharedServiceStart proto.InternalMessageInfo

// TenantSharedServiceStop is recorded when a tenant server
// is shut down inside the same process as the KV layer.
type TenantSharedServiceStop struct {
	logpb.CommonEventDetails        `protobuf:"bytes,1,opt,name=common,proto3,embedded=common" json:""`
	CommonSharedServiceEventDetails `protobuf:"bytes,2,opt,name=shared,proto3,embedded=shared" json:""`
}

func (m *TenantSharedServiceStop) Reset()         { *m = TenantSharedServiceStop{} }
func (m *TenantSharedServiceStop) String() string { return proto.CompactTextString(m) }
func (*TenantSharedServiceStop) ProtoMessage()    {}
func (*TenantSharedServiceStop) Descriptor() ([]byte, []int) {
	return fileDescriptor_7419df72f0fda340, []int{12}
}
func (m *TenantSharedServiceStop) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *TenantSharedServiceStop) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *TenantSharedServiceStop) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TenantSharedServiceStop.Merge(m, src)
}
func (m *TenantSharedServiceStop) XXX_Size() int {
	return m.Size()
}
func (m *TenantSharedServiceStop) XXX_DiscardUnknown() {
	xxx_messageInfo_TenantSharedServiceStop.DiscardUnknown(m)
}

var xxx_messageInfo_TenantSharedServiceStop proto.InternalMessageInfo

func init() {
	proto.RegisterType((*CommonNodeEventDetails)(nil), "cockroach.util.log.eventpb.CommonNodeEventDetails")
	proto.RegisterType((*NodeJoin)(nil), "cockroach.util.log.eventpb.NodeJoin")
	proto.RegisterType((*NodeRestart)(nil), "cockroach.util.log.eventpb.NodeRestart")
	proto.RegisterType((*NodeShutdownConnectionTimeout)(nil), "cockroach.util.log.eventpb.NodeShutdownConnectionTimeout")
	proto.RegisterType((*NodeShutdownTransactionTimeout)(nil), "cockroach.util.log.eventpb.NodeShutdownTransactionTimeout")
	proto.RegisterType((*CommonNodeDecommissionDetails)(nil), "cockroach.util.log.eventpb.CommonNodeDecommissionDetails")
	proto.RegisterType((*NodeDecommissioning)(nil), "cockroach.util.log.eventpb.NodeDecommissioning")
	proto.RegisterType((*NodeDecommissioned)(nil), "cockroach.util.log.eventpb.NodeDecommissioned")
	proto.RegisterType((*NodeRecommissioned)(nil), "cockroach.util.log.eventpb.NodeRecommissioned")
	proto.RegisterType((*CertsReload)(nil), "cockroach.util.log.eventpb.CertsReload")
	proto.RegisterType((*CommonSharedServiceEventDetails)(nil), "cockroach.util.log.eventpb.CommonSharedServiceEventDetails")
	proto.RegisterType((*TenantSharedServiceStart)(nil), "cockroach.util.log.eventpb.TenantSharedServiceStart")
	proto.RegisterType((*TenantSharedServiceStop)(nil), "cockroach.util.log.eventpb.TenantSharedServiceStop")
}

func init() {
	proto.RegisterFile("util/log/eventpb/cluster_events.proto", fileDescriptor_7419df72f0fda340)
}

var fileDescriptor_7419df72f0fda340 = []byte{
	// 901 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x57, 0xcf, 0x6f, 0xe3, 0x44,
	0x14, 0x8e, 0x93, 0x6e, 0x9a, 0xbe, 0xb4, 0xd5, 0x62, 0xba, 0x10, 0x45, 0xac, 0xbd, 0xb2, 0xf8,
	0xd1, 0xc3, 0xe2, 0x88, 0x5d, 0x21, 0x7e, 0x89, 0x03, 0x69, 0x41, 0x0a, 0xb0, 0x0b, 0x72, 0x02,
	0x2b, 0xc1, 0x21, 0x9a, 0xd8, 0x0f, 0x77, 0x54, 0x7b, 0x26, 0xcc, 0x8c, 0x4b, 0xf9, 0x2f, 0xf8,
	0x1f, 0xb8, 0x23, 0x71, 0x01, 0x89, 0x0b, 0x1c, 0x2b, 0x4e, 0x3d, 0xae, 0x38, 0x58, 0xe0, 0x5e,
	0x50, 0x8f, 0xdc, 0x91, 0x90, 0xc7, 0x4e, 0xb6, 0x49, 0x13, 0x40, 0xa2, 0x1c, 0x22, 0xed, 0x29,
	0x8e, 0xdf, 0xf7, 0xbe, 0xf7, 0xde, 0x37, 0xcf, 0x6f, 0x66, 0xe0, 0xb9, 0x44, 0xd1, 0xa8, 0x13,
	0xf1, 0xb0, 0x83, 0x47, 0xc8, 0xd4, 0x78, 0xd4, 0xf1, 0xa3, 0x44, 0x2a, 0x14, 0x43, 0xfd, 0x5f,
	0xba, 0x63, 0xc1, 0x15, 0x37, 0xdb, 0x3e, 0xf7, 0x0f, 0x05, 0x27, 0xfe, 0x81, 0x9b, 0x3b, 0xb8,
	0x11, 0x0f, 0xdd, 0xd2, 0xa1, 0xbd, 0x13, 0xf2, 0x90, 0x6b, 0x58, 0x27, 0x7f, 0x2a, 0x3c, 0xda,
	0xed, 0x29, 0x71, 0xc4, 0xc3, 0xf1, 0xa8, 0xa0, 0x2f, 0x6c, 0xce, 0xd7, 0x06, 0x3c, 0xb5, 0xc7,
	0xe3, 0x98, 0xb3, 0xfb, 0x3c, 0xc0, 0xb7, 0x73, 0xcb, 0x3e, 0x2a, 0x42, 0x23, 0x69, 0xbe, 0x04,
	0xeb, 0x8c, 0x07, 0x38, 0xa4, 0x41, 0xcb, 0xb8, 0x65, 0xec, 0x5e, 0xeb, 0xb6, 0xb2, 0xd4, 0xae,
	0xe7, 0xb0, 0xde, 0xfe, 0x79, 0x6a, 0xc3, 0x6d, 0x1e, 0x53, 0x85, 0xf1, 0x58, 0x7d, 0xe9, 0xd5,
	0x73, 0x60, 0x2f, 0x30, 0x5f, 0x04, 0x90, 0x8a, 0x08, 0x85, 0xc1, 0x90, 0xa8, 0x56, 0xed, 0x96,
	0xb1, 0x5b, 0xeb, 0x6e, 0xcf, 0x61, 0x37, 0x4a, 0xc4, 0x5b, 0xca, 0x7c, 0x01, 0xd6, 0x23, 0x22,
	0xd5, 0x30, 0x19, 0xb7, 0xd6, 0x16, 0x62, 0xeb, 0xb9, 0xf9, 0xa3, 0xb1, 0xf3, 0x8d, 0x01, 0x8d,
	0x3c, 0xf0, 0xbb, 0x9c, 0x32, 0xf3, 0x7d, 0xa8, 0xfb, 0x3a, 0x63, 0x9d, 0x56, 0xf3, 0xce, 0xf3,
	0xee, 0x02, 0x45, 0x8a, 0x9a, 0x2e, 0xd6, 0xd3, 0xdd, 0x3c, 0x49, 0xed, 0xca, 0x69, 0x6a, 0x1b,
	0xe7, 0xa9, 0x5d, 0xf1, 0x4a, 0x0e, 0x73, 0x00, 0x6b, 0x79, 0xf2, 0xad, 0xaa, 0xe6, 0xba, 0xe3,
	0x2e, 0x57, 0xd7, 0x5d, 0xac, 0xd3, 0x1c, 0xaf, 0x66, 0x73, 0xbe, 0x35, 0xa0, 0x99, 0x03, 0x3d,
	0xd4, 0xd5, 0xae, 0x44, 0xce, 0xdf, 0xd5, 0xe0, 0x66, 0x0e, 0xec, 0x1f, 0x24, 0x2a, 0xe0, 0x5f,
	0xb0, 0x3d, 0xce, 0x18, 0xfa, 0x8a, 0x72, 0x36, 0xa0, 0x31, 0xf2, 0x64, 0x25, 0xaa, 0x30, 0x39,
	0xd4, 0x03, 0x6d, 0xd6, 0xed, 0xb7, 0xd1, 0x7d, 0x90, 0x63, 0x7e, 0x49, 0xed, 0xdd, 0x90, 0xaa,
	0x83, 0x64, 0xe4, 0xfa, 0x3c, 0xee, 0x4c, 0x23, 0x05, 0xa3, 0x8e, 0xc0, 0x80, 0xf8, 0xca, 0xed,
	0x93, 0xcf, 0xb0, 0xaf, 0x04, 0x65, 0xe1, 0x6c, 0x0b, 0xfe, 0x91, 0xda, 0x37, 0x0a, 0xc8, 0xeb,
	0x0e, 0xe3, 0x4c, 0x22, 0x93, 0x54, 0xd1, 0x23, 0x74, 0xbc, 0x32, 0x8c, 0xf9, 0x0e, 0xdc, 0xf0,
	0xa7, 0x4a, 0xc9, 0xa1, 0xc0, 0x98, 0x50, 0x46, 0x59, 0xa8, 0x5b, 0x7a, 0xab, 0xfb, 0xc4, 0x79,
	0x6a, 0x6f, 0xdd, 0xa6, 0xcc, 0x8f, 0x92, 0x00, 0x8b, 0xae, 0xde, 0xb9, 0x80, 0xf7, 0x26, 0x70,
	0xf3, 0x55, 0xd8, 0x56, 0x85, 0xce, 0xc3, 0x98, 0x46, 0x11, 0x95, 0xad, 0x6b, 0xcb, 0x08, 0xb6,
	0x4a, 0xe0, 0x3d, 0x8d, 0x73, 0xbe, 0xaf, 0x81, 0x75, 0x71, 0xe1, 0x06, 0x82, 0x30, 0x49, 0x1e,
	0xaf, 0xdc, 0x0a, 0xac, 0x9c, 0x01, 0x37, 0x1f, 0x29, 0xb4, 0x8f, 0xb9, 0xbe, 0x54, 0x4a, 0xca,
	0xd9, 0x64, 0x08, 0x7f, 0x08, 0xa6, 0xc0, 0xcf, 0x13, 0x94, 0x8a, 0xb2, 0x70, 0x38, 0x3b, 0x8f,
	0x9d, 0x2c, 0xb5, 0xaf, 0x7b, 0x53, 0xeb, 0xc2, 0xc9, 0x7c, 0x5d, 0xcc, 0xda, 0x03, 0x73, 0x1f,
	0xb6, 0x15, 0x11, 0x21, 0xaa, 0x29, 0x5b, 0x55, 0xb3, 0x59, 0x59, 0x6a, 0x6f, 0x0e, 0xb4, 0x65,
	0x21, 0xd3, 0xa6, 0x7a, 0x64, 0x0b, 0x9c, 0x9f, 0x0c, 0x78, 0x72, 0x3e, 0xe7, 0x5c, 0x8b, 0xab,
	0x6d, 0xb4, 0x4f, 0x67, 0x1a, 0xed, 0xb5, 0x7f, 0xd7, 0x68, 0x0b, 0x64, 0x5c, 0x38, 0xef, 0x7e,
	0x34, 0xc0, 0x9c, 0xc7, 0x63, 0xb0, 0x8a, 0x15, 0x78, 0x2b, 0x5b, 0xc1, 0x0f, 0x06, 0x34, 0xf7,
	0x50, 0x28, 0xe9, 0x61, 0xc4, 0xc9, 0x55, 0xa7, 0xbe, 0x0b, 0xeb, 0x32, 0xf1, 0x7d, 0x94, 0x52,
	0x67, 0xdf, 0xb8, 0x74, 0xbe, 0x98, 0x98, 0xcd, 0xbb, 0xb0, 0x85, 0x42, 0x70, 0x31, 0x8c, 0x51,
	0x4a, 0x12, 0x62, 0x39, 0x82, 0xe6, 0xf1, 0x9b, 0x1a, 0x74, 0xaf, 0xc0, 0x38, 0x7f, 0x1a, 0x60,
	0x17, 0xb9, 0xf4, 0x0f, 0x88, 0xc0, 0xa0, 0x8f, 0xe2, 0x88, 0xfa, 0xff, 0xf9, 0x10, 0xf5, 0x0a,
	0x6c, 0x28, 0x64, 0x84, 0xa9, 0xc9, 0xb7, 0xb9, 0xd6, 0x6d, 0x67, 0xa9, 0xdd, 0x18, 0xe8, 0x97,
	0x97, 0xdc, 0x1a, 0x05, 0xb8, 0x17, 0x98, 0x6f, 0x42, 0x93, 0x32, 0xa9, 0x08, 0xf3, 0x75, 0xbc,
	0x9a, 0x8e, 0xf7, 0x4c, 0x96, 0xda, 0xd0, 0x2b, 0x5f, 0x5f, 0x72, 0x86, 0x89, 0x43, 0x2f, 0x30,
	0x3b, 0xd0, 0x2c, 0xe3, 0x32, 0x12, 0xa3, 0x1e, 0x82, 0x97, 0x15, 0x80, 0x02, 0x72, 0x9f, 0xc4,
	0xe8, 0xfc, 0x5e, 0x85, 0x56, 0x91, 0xd4, 0x4c, 0xfd, 0xfd, 0xff, 0xe1, 0xc4, 0x43, 0xa0, 0x2e,
	0x75, 0x8c, 0xb2, 0x0d, 0xdf, 0xf8, 0xe7, 0x36, 0x5c, 0xba, 0x26, 0xf3, 0x21, 0x0a, 0x62, 0xf3,
	0x59, 0xa8, 0xf2, 0x43, 0x2d, 0x5a, 0xa3, 0xbb, 0x93, 0xa5, 0x76, 0xf5, 0x83, 0xf7, 0xe6, 0x6a,
	0xaf, 0xf2, 0x43, 0x33, 0x01, 0x28, 0x1a, 0x45, 0xe1, 0xb1, 0x2a, 0x35, 0xfa, 0xb8, 0xdc, 0xa8,
	0xdc, 0xbf, 0xdf, 0xa8, 0x3c, 0xfd, 0x43, 0x46, 0xd1, 0xb2, 0xed, 0x6a, 0x7b, 0xb2, 0x5d, 0xc5,
	0xf4, 0x18, 0x03, 0xc7, 0xdb, 0xd0, 0x91, 0x06, 0x78, 0xac, 0x9c, 0x9f, 0x0d, 0x78, 0x7a, 0xa1,
	0xd4, 0x7c, 0xbc, 0x72, 0x4a, 0x77, 0x1f, 0x9c, 0xfc, 0x66, 0x55, 0x4e, 0x32, 0xcb, 0x38, 0xcd,
	0x2c, 0xe3, 0x61, 0x66, 0x19, 0xbf, 0x66, 0x96, 0xf1, 0xd5, 0x99, 0x55, 0x39, 0x3d, 0xb3, 0x2a,
	0x0f, 0xcf, 0xac, 0xca, 0x27, 0x2f, 0x2f, 0x51, 0x72, 0xfa, 0xdc, 0x19, 0x1f, 0x86, 0x9d, 0xf9,
	0xfb, 0xd2, 0xa8, 0xae, 0xef, 0x34, 0x77, 0xff, 0x0a, 0x00, 0x00, 0xff, 0xff, 0x6c, 0x7c, 0x5d,
	0x7c, 0x4a, 0x0d, 0x00, 0x00,
}

func (m *CommonNodeEventDetails) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CommonNodeEventDetails) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CommonNodeEventDetails) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.LastUp != 0 {
		i = encodeVarintClusterEvents(dAtA, i, uint64(m.LastUp))
		i--
		dAtA[i] = 0x20
	}
	if m.StartedAt != 0 {
		i = encodeVarintClusterEvents(dAtA, i, uint64(m.StartedAt))
		i--
		dAtA[i] = 0x18
	}
	if m.NodeID != 0 {
		i = encodeVarintClusterEvents(dAtA, i, uint64(m.NodeID))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *NodeJoin) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *NodeJoin) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *NodeJoin) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.CommonNodeEventDetails.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintClusterEvents(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	{
		size, err := m.CommonEventDetails.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintClusterEvents(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *NodeRestart) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *NodeRestart) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *NodeRestart) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.CommonNodeEventDetails.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintClusterEvents(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	{
		size, err := m.CommonEventDetails.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintClusterEvents(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *NodeShutdownConnectionTimeout) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *NodeShutdownConnectionTimeout) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *NodeShutdownConnectionTimeout) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.TimeoutMillis != 0 {
		i = encodeVarintClusterEvents(dAtA, i, uint64(m.TimeoutMillis))
		i--
		dAtA[i] = 0x28
	}
	if m.ConnectionsRemaining != 0 {
		i = encodeVarintClusterEvents(dAtA, i, uint64(m.ConnectionsRemaining))
		i--
		dAtA[i] = 0x20
	}
	if len(m.Detail) > 0 {
		i -= len(m.Detail)
		copy(dAtA[i:], m.Detail)
		i = encodeVarintClusterEvents(dAtA, i, uint64(len(m.Detail)))
		i--
		dAtA[i] = 0x1a
	}
	{
		size, err := m.CommonNodeEventDetails.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintClusterEvents(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	{
		size, err := m.CommonEventDetails.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintClusterEvents(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *NodeShutdownTransactionTimeout) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *NodeShutdownTransactionTimeout) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *NodeShutdownTransactionTimeout) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.TimeoutMillis != 0 {
		i = encodeVarintClusterEvents(dAtA, i, uint64(m.TimeoutMillis))
		i--
		dAtA[i] = 0x28
	}
	if m.ConnectionsRemaining != 0 {
		i = encodeVarintClusterEvents(dAtA, i, uint64(m.ConnectionsRemaining))
		i--
		dAtA[i] = 0x20
	}
	if len(m.Detail) > 0 {
		i -= len(m.Detail)
		copy(dAtA[i:], m.Detail)
		i = encodeVarintClusterEvents(dAtA, i, uint64(len(m.Detail)))
		i--
		dAtA[i] = 0x1a
	}
	{
		size, err := m.CommonNodeEventDetails.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintClusterEvents(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	{
		size, err := m.CommonEventDetails.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintClusterEvents(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *CommonNodeDecommissionDetails) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CommonNodeDecommissionDetails) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CommonNodeDecommissionDetails) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.TargetNodeID != 0 {
		i = encodeVarintClusterEvents(dAtA, i, uint64(m.TargetNodeID))
		i--
		dAtA[i] = 0x10
	}
	if m.RequestingNodeID != 0 {
		i = encodeVarintClusterEvents(dAtA, i, uint64(m.RequestingNodeID))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *NodeDecommissioning) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *NodeDecommissioning) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *NodeDecommissioning) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.CommonNodeDecommissionDetails.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintClusterEvents(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	{
		size, err := m.CommonEventDetails.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintClusterEvents(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *NodeDecommissioned) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *NodeDecommissioned) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *NodeDecommissioned) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.CommonNodeDecommissionDetails.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintClusterEvents(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	{
		size, err := m.CommonEventDetails.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintClusterEvents(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *NodeRecommissioned) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *NodeRecommissioned) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *NodeRecommissioned) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.CommonNodeDecommissionDetails.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintClusterEvents(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	{
		size, err := m.CommonEventDetails.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintClusterEvents(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *CertsReload) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CertsReload) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CertsReload) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ErrorMessage) > 0 {
		i -= len(m.ErrorMessage)
		copy(dAtA[i:], m.ErrorMessage)
		i = encodeVarintClusterEvents(dAtA, i, uint64(len(m.ErrorMessage)))
		i--
		dAtA[i] = 0x1a
	}
	if m.Success {
		i--
		if m.Success {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x10
	}
	{
		size, err := m.CommonEventDetails.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintClusterEvents(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *CommonSharedServiceEventDetails) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CommonSharedServiceEventDetails) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CommonSharedServiceEventDetails) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.TenantName) > 0 {
		i -= len(m.TenantName)
		copy(dAtA[i:], m.TenantName)
		i = encodeVarintClusterEvents(dAtA, i, uint64(len(m.TenantName)))
		i--
		dAtA[i] = 0x22
	}
	if m.InstanceID != 0 {
		i = encodeVarintClusterEvents(dAtA, i, uint64(m.InstanceID))
		i--
		dAtA[i] = 0x18
	}
	if m.TenantID != 0 {
		i = encodeVarintClusterEvents(dAtA, i, uint64(m.TenantID))
		i--
		dAtA[i] = 0x10
	}
	if m.NodeID != 0 {
		i = encodeVarintClusterEvents(dAtA, i, uint64(m.NodeID))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *TenantSharedServiceStart) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *TenantSharedServiceStart) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *TenantSharedServiceStart) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ErrorText) > 0 {
		i -= len(m.ErrorText)
		copy(dAtA[i:], m.ErrorText)
		i = encodeVarintClusterEvents(dAtA, i, uint64(len(m.ErrorText)))
		i--
		dAtA[i] = 0x22
	}
	if m.OK {
		i--
		if m.OK {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x18
	}
	{
		size, err := m.CommonSharedServiceEventDetails.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintClusterEvents(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	{
		size, err := m.CommonEventDetails.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintClusterEvents(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *TenantSharedServiceStop) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *TenantSharedServiceStop) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *TenantSharedServiceStop) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.CommonSharedServiceEventDetails.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintClusterEvents(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	{
		size, err := m.CommonEventDetails.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintClusterEvents(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintClusterEvents(dAtA []byte, offset int, v uint64) int {
	offset -= sovClusterEvents(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *CommonNodeEventDetails) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.NodeID != 0 {
		n += 1 + sovClusterEvents(uint64(m.NodeID))
	}
	if m.StartedAt != 0 {
		n += 1 + sovClusterEvents(uint64(m.StartedAt))
	}
	if m.LastUp != 0 {
		n += 1 + sovClusterEvents(uint64(m.LastUp))
	}
	return n
}

func (m *NodeJoin) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.CommonEventDetails.Size()
	n += 1 + l + sovClusterEvents(uint64(l))
	l = m.CommonNodeEventDetails.Size()
	n += 1 + l + sovClusterEvents(uint64(l))
	return n
}

func (m *NodeRestart) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.CommonEventDetails.Size()
	n += 1 + l + sovClusterEvents(uint64(l))
	l = m.CommonNodeEventDetails.Size()
	n += 1 + l + sovClusterEvents(uint64(l))
	return n
}

func (m *NodeShutdownConnectionTimeout) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.CommonEventDetails.Size()
	n += 1 + l + sovClusterEvents(uint64(l))
	l = m.CommonNodeEventDetails.Size()
	n += 1 + l + sovClusterEvents(uint64(l))
	l = len(m.Detail)
	if l > 0 {
		n += 1 + l + sovClusterEvents(uint64(l))
	}
	if m.ConnectionsRemaining != 0 {
		n += 1 + sovClusterEvents(uint64(m.ConnectionsRemaining))
	}
	if m.TimeoutMillis != 0 {
		n += 1 + sovClusterEvents(uint64(m.TimeoutMillis))
	}
	return n
}

func (m *NodeShutdownTransactionTimeout) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.CommonEventDetails.Size()
	n += 1 + l + sovClusterEvents(uint64(l))
	l = m.CommonNodeEventDetails.Size()
	n += 1 + l + sovClusterEvents(uint64(l))
	l = len(m.Detail)
	if l > 0 {
		n += 1 + l + sovClusterEvents(uint64(l))
	}
	if m.ConnectionsRemaining != 0 {
		n += 1 + sovClusterEvents(uint64(m.ConnectionsRemaining))
	}
	if m.TimeoutMillis != 0 {
		n += 1 + sovClusterEvents(uint64(m.TimeoutMillis))
	}
	return n
}

func (m *CommonNodeDecommissionDetails) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.RequestingNodeID != 0 {
		n += 1 + sovClusterEvents(uint64(m.RequestingNodeID))
	}
	if m.TargetNodeID != 0 {
		n += 1 + sovClusterEvents(uint64(m.TargetNodeID))
	}
	return n
}

func (m *NodeDecommissioning) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.CommonEventDetails.Size()
	n += 1 + l + sovClusterEvents(uint64(l))
	l = m.CommonNodeDecommissionDetails.Size()
	n += 1 + l + sovClusterEvents(uint64(l))
	return n
}

func (m *NodeDecommissioned) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.CommonEventDetails.Size()
	n += 1 + l + sovClusterEvents(uint64(l))
	l = m.CommonNodeDecommissionDetails.Size()
	n += 1 + l + sovClusterEvents(uint64(l))
	return n
}

func (m *NodeRecommissioned) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.CommonEventDetails.Size()
	n += 1 + l + sovClusterEvents(uint64(l))
	l = m.CommonNodeDecommissionDetails.Size()
	n += 1 + l + sovClusterEvents(uint64(l))
	return n
}

func (m *CertsReload) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.CommonEventDetails.Size()
	n += 1 + l + sovClusterEvents(uint64(l))
	if m.Success {
		n += 2
	}
	l = len(m.ErrorMessage)
	if l > 0 {
		n += 1 + l + sovClusterEvents(uint64(l))
	}
	return n
}

func (m *CommonSharedServiceEventDetails) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.NodeID != 0 {
		n += 1 + sovClusterEvents(uint64(m.NodeID))
	}
	if m.TenantID != 0 {
		n += 1 + sovClusterEvents(uint64(m.TenantID))
	}
	if m.InstanceID != 0 {
		n += 1 + sovClusterEvents(uint64(m.InstanceID))
	}
	l = len(m.TenantName)
	if l > 0 {
		n += 1 + l + sovClusterEvents(uint64(l))
	}
	return n
}

func (m *TenantSharedServiceStart) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.CommonEventDetails.Size()
	n += 1 + l + sovClusterEvents(uint64(l))
	l = m.CommonSharedServiceEventDetails.Size()
	n += 1 + l + sovClusterEvents(uint64(l))
	if m.OK {
		n += 2
	}
	l = len(m.ErrorText)
	if l > 0 {
		n += 1 + l + sovClusterEvents(uint64(l))
	}
	return n
}

func (m *TenantSharedServiceStop) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.CommonEventDetails.Size()
	n += 1 + l + sovClusterEvents(uint64(l))
	l = m.CommonSharedServiceEventDetails.Size()
	n += 1 + l + sovClusterEvents(uint64(l))
	return n
}

func sovClusterEvents(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozClusterEvents(x uint64) (n int) {
	return sovClusterEvents(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *CommonNodeEventDetails) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowClusterEvents
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CommonNodeEventDetails: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CommonNodeEventDetails: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NodeID", wireType)
			}
			m.NodeID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClusterEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NodeID |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field StartedAt", wireType)
			}
			m.StartedAt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClusterEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.StartedAt |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastUp", wireType)
			}
			m.LastUp = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClusterEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LastUp |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipClusterEvents(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthClusterEvents
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *NodeJoin) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowClusterEvents
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: NodeJoin: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: NodeJoin: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CommonEventDetails", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClusterEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthClusterEvents
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthClusterEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.CommonEventDetails.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CommonNodeEventDetails", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClusterEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthClusterEvents
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthClusterEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.CommonNodeEventDetails.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipClusterEvents(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthClusterEvents
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *NodeRestart) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowClusterEvents
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: NodeRestart: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: NodeRestart: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CommonEventDetails", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClusterEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthClusterEvents
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthClusterEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.CommonEventDetails.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CommonNodeEventDetails", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClusterEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthClusterEvents
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthClusterEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.CommonNodeEventDetails.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipClusterEvents(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthClusterEvents
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *NodeShutdownConnectionTimeout) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowClusterEvents
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: NodeShutdownConnectionTimeout: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: NodeShutdownConnectionTimeout: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CommonEventDetails", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClusterEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthClusterEvents
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthClusterEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.CommonEventDetails.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CommonNodeEventDetails", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClusterEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthClusterEvents
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthClusterEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.CommonNodeEventDetails.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Detail", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClusterEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthClusterEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthClusterEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Detail = github_com_cockroachdb_redact.SafeString(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ConnectionsRemaining", wireType)
			}
			m.ConnectionsRemaining = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClusterEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ConnectionsRemaining |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TimeoutMillis", wireType)
			}
			m.TimeoutMillis = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClusterEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TimeoutMillis |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipClusterEvents(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthClusterEvents
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *NodeShutdownTransactionTimeout) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowClusterEvents
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: NodeShutdownTransactionTimeout: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: NodeShutdownTransactionTimeout: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CommonEventDetails", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClusterEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthClusterEvents
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthClusterEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.CommonEventDetails.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CommonNodeEventDetails", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClusterEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthClusterEvents
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthClusterEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.CommonNodeEventDetails.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Detail", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClusterEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthClusterEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthClusterEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Detail = github_com_cockroachdb_redact.SafeString(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ConnectionsRemaining", wireType)
			}
			m.ConnectionsRemaining = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClusterEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ConnectionsRemaining |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TimeoutMillis", wireType)
			}
			m.TimeoutMillis = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClusterEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TimeoutMillis |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipClusterEvents(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthClusterEvents
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *CommonNodeDecommissionDetails) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowClusterEvents
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CommonNodeDecommissionDetails: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CommonNodeDecommissionDetails: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RequestingNodeID", wireType)
			}
			m.RequestingNodeID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClusterEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RequestingNodeID |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TargetNodeID", wireType)
			}
			m.TargetNodeID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClusterEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TargetNodeID |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipClusterEvents(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthClusterEvents
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *NodeDecommissioning) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowClusterEvents
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: NodeDecommissioning: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: NodeDecommissioning: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CommonEventDetails", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClusterEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthClusterEvents
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthClusterEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.CommonEventDetails.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CommonNodeDecommissionDetails", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClusterEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthClusterEvents
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthClusterEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.CommonNodeDecommissionDetails.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipClusterEvents(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthClusterEvents
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *NodeDecommissioned) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowClusterEvents
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: NodeDecommissioned: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: NodeDecommissioned: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CommonEventDetails", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClusterEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthClusterEvents
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthClusterEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.CommonEventDetails.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CommonNodeDecommissionDetails", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClusterEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthClusterEvents
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthClusterEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.CommonNodeDecommissionDetails.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipClusterEvents(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthClusterEvents
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *NodeRecommissioned) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowClusterEvents
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: NodeRecommissioned: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: NodeRecommissioned: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CommonEventDetails", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClusterEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthClusterEvents
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthClusterEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.CommonEventDetails.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CommonNodeDecommissionDetails", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClusterEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthClusterEvents
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthClusterEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.CommonNodeDecommissionDetails.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipClusterEvents(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthClusterEvents
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *CertsReload) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowClusterEvents
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CertsReload: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CertsReload: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CommonEventDetails", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClusterEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthClusterEvents
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthClusterEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.CommonEventDetails.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Success", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClusterEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Success = bool(v != 0)
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ErrorMessage", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClusterEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthClusterEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthClusterEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ErrorMessage = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipClusterEvents(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthClusterEvents
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *CommonSharedServiceEventDetails) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowClusterEvents
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CommonSharedServiceEventDetails: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CommonSharedServiceEventDetails: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NodeID", wireType)
			}
			m.NodeID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClusterEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NodeID |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TenantID", wireType)
			}
			m.TenantID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClusterEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TenantID |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field InstanceID", wireType)
			}
			m.InstanceID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClusterEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.InstanceID |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TenantName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClusterEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthClusterEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthClusterEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TenantName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipClusterEvents(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthClusterEvents
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *TenantSharedServiceStart) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowClusterEvents
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: TenantSharedServiceStart: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: TenantSharedServiceStart: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CommonEventDetails", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClusterEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthClusterEvents
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthClusterEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.CommonEventDetails.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CommonSharedServiceEventDetails", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClusterEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthClusterEvents
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthClusterEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.CommonSharedServiceEventDetails.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field OK", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClusterEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.OK = bool(v != 0)
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ErrorText", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClusterEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthClusterEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthClusterEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ErrorText = github_com_cockroachdb_redact.RedactableString(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipClusterEvents(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthClusterEvents
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *TenantSharedServiceStop) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowClusterEvents
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: TenantSharedServiceStop: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: TenantSharedServiceStop: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CommonEventDetails", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClusterEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthClusterEvents
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthClusterEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.CommonEventDetails.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CommonSharedServiceEventDetails", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClusterEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthClusterEvents
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthClusterEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.CommonSharedServiceEventDetails.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipClusterEvents(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthClusterEvents
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipClusterEvents(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowClusterEvents
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowClusterEvents
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowClusterEvents
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthClusterEvents
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupClusterEvents
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthClusterEvents
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthClusterEvents        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowClusterEvents          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupClusterEvents = fmt.Errorf("proto: unexpected end of group")
)
