// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: util/log/eventpb/zone_events.proto

package eventpb

import (
	fmt "fmt"
	logpb "github.com/cockroachdb/cockroach/pkg/util/log/logpb"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// CommonZoneConfigDetails is common to zone config change events.
type CommonZoneConfigDetails struct {
	// The target object of the zone config change.
	Target string `protobuf:"bytes,1,opt,name=target,proto3" json:",omitempty"`
	// The applied zone config in YAML format.
	Config string `protobuf:"bytes,2,opt,name=config,proto3" json:",omitempty"`
	// The SQL representation of the applied zone config options.
	Options []string `protobuf:"bytes,3,rep,name=options,proto3" json:",omitempty"`
}

func (m *CommonZoneConfigDetails) Reset()         { *m = CommonZoneConfigDetails{} }
func (m *CommonZoneConfigDetails) String() string { return proto.CompactTextString(m) }
func (*CommonZoneConfigDetails) ProtoMessage()    {}
func (*CommonZoneConfigDetails) Descriptor() ([]byte, []int) {
	return fileDescriptor_91ba991379bae0fd, []int{0}
}
func (m *CommonZoneConfigDetails) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CommonZoneConfigDetails) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *CommonZoneConfigDetails) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommonZoneConfigDetails.Merge(m, src)
}
func (m *CommonZoneConfigDetails) XXX_Size() int {
	return m.Size()
}
func (m *CommonZoneConfigDetails) XXX_DiscardUnknown() {
	xxx_messageInfo_CommonZoneConfigDetails.DiscardUnknown(m)
}

var xxx_messageInfo_CommonZoneConfigDetails proto.InternalMessageInfo

// SetZoneConfig is recorded when a zone config is changed.
type SetZoneConfig struct {
	logpb.CommonEventDetails `protobuf:"bytes,1,opt,name=common,proto3,embedded=common" json:""`
	CommonSQLEventDetails    `protobuf:"bytes,2,opt,name=sql,proto3,embedded=sql" json:""`
	CommonZoneConfigDetails  `protobuf:"bytes,3,opt,name=config,proto3,embedded=config" json:""`
}

func (m *SetZoneConfig) Reset()         { *m = SetZoneConfig{} }
func (m *SetZoneConfig) String() string { return proto.CompactTextString(m) }
func (*SetZoneConfig) ProtoMessage()    {}
func (*SetZoneConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_91ba991379bae0fd, []int{1}
}
func (m *SetZoneConfig) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SetZoneConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *SetZoneConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetZoneConfig.Merge(m, src)
}
func (m *SetZoneConfig) XXX_Size() int {
	return m.Size()
}
func (m *SetZoneConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_SetZoneConfig.DiscardUnknown(m)
}

var xxx_messageInfo_SetZoneConfig proto.InternalMessageInfo

// RemoveZoneConfig is recorded when a zone config is removed.
type RemoveZoneConfig struct {
	logpb.CommonEventDetails `protobuf:"bytes,1,opt,name=common,proto3,embedded=common" json:""`
	CommonSQLEventDetails    `protobuf:"bytes,2,opt,name=sql,proto3,embedded=sql" json:""`
	CommonZoneConfigDetails  `protobuf:"bytes,3,opt,name=config,proto3,embedded=config" json:""`
}

func (m *RemoveZoneConfig) Reset()         { *m = RemoveZoneConfig{} }
func (m *RemoveZoneConfig) String() string { return proto.CompactTextString(m) }
func (*RemoveZoneConfig) ProtoMessage()    {}
func (*RemoveZoneConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_91ba991379bae0fd, []int{2}
}
func (m *RemoveZoneConfig) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RemoveZoneConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *RemoveZoneConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveZoneConfig.Merge(m, src)
}
func (m *RemoveZoneConfig) XXX_Size() int {
	return m.Size()
}
func (m *RemoveZoneConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveZoneConfig.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveZoneConfig proto.InternalMessageInfo

func init() {
	proto.RegisterType((*CommonZoneConfigDetails)(nil), "cockroach.util.log.eventpb.CommonZoneConfigDetails")
	proto.RegisterType((*SetZoneConfig)(nil), "cockroach.util.log.eventpb.SetZoneConfig")
	proto.RegisterType((*RemoveZoneConfig)(nil), "cockroach.util.log.eventpb.RemoveZoneConfig")
}

func init() {
	proto.RegisterFile("util/log/eventpb/zone_events.proto", fileDescriptor_91ba991379bae0fd)
}

var fileDescriptor_91ba991379bae0fd = []byte{
	// 376 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x93, 0xc1, 0x6a, 0xea, 0x40,
	0x18, 0x85, 0x33, 0x06, 0xbc, 0xdc, 0xf1, 0xde, 0xcb, 0x25, 0x14, 0x2a, 0x81, 0x4e, 0x24, 0x0b,
	0x71, 0x51, 0x12, 0xaa, 0xf4, 0x05, 0xb4, 0xdd, 0xb9, 0x51, 0x17, 0xa5, 0x6e, 0x8a, 0x49, 0xa7,
	0x63, 0x30, 0xc9, 0x9f, 0x9a, 0x51, 0x68, 0x5f, 0xa1, 0x50, 0x0a, 0x7d, 0x29, 0x97, 0x2e, 0x5d,
	0x85, 0x36, 0xee, 0x7c, 0x8a, 0x32, 0x93, 0xa8, 0xa5, 0xda, 0xf6, 0x05, 0xba, 0x9b, 0xe1, 0x9c,
	0xf9, 0xe6, 0xfc, 0x07, 0x7e, 0x6c, 0x4e, 0xb8, 0xe7, 0xdb, 0x3e, 0x30, 0x9b, 0x4e, 0x69, 0xc8,
	0x23, 0xc7, 0xbe, 0x87, 0x90, 0x5e, 0xc9, 0x4b, 0x6c, 0x45, 0x63, 0xe0, 0xa0, 0xe9, 0x2e, 0xb8,
	0xa3, 0x31, 0x0c, 0xdc, 0xa1, 0x25, 0xdc, 0x96, 0x0f, 0xcc, 0xca, 0xdd, 0xfa, 0x01, 0x03, 0x06,
	0xd2, 0x66, 0x8b, 0x53, 0xf6, 0x42, 0x3f, 0xda, 0xa1, 0xbe, 0x07, 0xea, 0xfa, 0x46, 0xf6, 0x81,
	0xad, 0xc5, 0x4c, 0x33, 0x9f, 0x11, 0x3e, 0x6c, 0x41, 0x10, 0x40, 0xd8, 0x87, 0x90, 0xb6, 0x20,
	0xbc, 0xf1, 0xd8, 0x19, 0xe5, 0x03, 0xcf, 0x8f, 0xb5, 0x2a, 0x2e, 0xf2, 0xc1, 0x98, 0x51, 0x5e,
	0x46, 0x15, 0x54, 0xfb, 0xdd, 0xfc, 0xb7, 0x4a, 0x0c, 0x7c, 0x0c, 0x81, 0xc7, 0x69, 0x10, 0xf1,
	0xbb, 0x6e, 0xae, 0x0a, 0x9f, 0x2b, 0x1f, 0x96, 0x0b, 0xfb, 0x7d, 0x99, 0xaa, 0xd5, 0xf0, 0x2f,
	0x88, 0xb8, 0x07, 0x61, 0x5c, 0x56, 0x2b, 0xea, 0x1e, 0xe3, 0x5a, 0x36, 0x1f, 0x0a, 0xf8, 0x6f,
	0x8f, 0xf2, 0x6d, 0x24, 0xad, 0x2d, 0xfe, 0x10, 0x31, 0x65, 0x96, 0x52, 0xbd, 0x6a, 0xed, 0x69,
	0x29, 0x1b, 0xe4, 0x5c, 0x8c, 0x97, 0xcf, 0xd0, 0xfc, 0x33, 0x4b, 0x0c, 0x65, 0x9e, 0x18, 0x68,
	0x95, 0x18, 0x4a, 0x37, 0x67, 0x68, 0x1d, 0xac, 0xc6, 0xb7, 0xbe, 0x8c, 0x5b, 0xaa, 0x9f, 0x58,
	0x9f, 0x17, 0x9e, 0x23, 0x7b, 0x9d, 0xf6, 0x17, 0x54, 0xc1, 0xd2, 0x2e, 0x37, 0x25, 0xa8, 0x92,
	0xda, 0xf8, 0x9e, 0xba, 0xd3, 0xf8, 0x6e, 0x5a, 0x21, 0x9a, 0x8f, 0x05, 0xfc, 0xbf, 0x4b, 0x03,
	0x98, 0xd2, 0x9f, 0x42, 0x84, 0xd8, 0xbc, 0x98, 0xbd, 0x12, 0x65, 0x96, 0x12, 0x34, 0x4f, 0x09,
	0x5a, 0xa4, 0x04, 0xbd, 0xa4, 0x04, 0x3d, 0x2d, 0x89, 0x32, 0x5f, 0x12, 0x65, 0xb1, 0x24, 0x4a,
	0xff, 0x94, 0x79, 0x7c, 0x38, 0x71, 0x2c, 0x17, 0x02, 0x7b, 0xf3, 0xed, 0xb5, 0xb3, 0x3d, 0xdb,
	0xd1, 0x88, 0xd9, 0x1f, 0xd7, 0xc6, 0x29, 0xca, 0xa5, 0x68, 0xbc, 0x05, 0x00, 0x00, 0xff, 0xff,
	0xf6, 0xac, 0xa8, 0xfa, 0xa7, 0x03, 0x00, 0x00,
}

func (m *CommonZoneConfigDetails) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CommonZoneConfigDetails) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CommonZoneConfigDetails) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Options) > 0 {
		for iNdEx := len(m.Options) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Options[iNdEx])
			copy(dAtA[i:], m.Options[iNdEx])
			i = encodeVarintZoneEvents(dAtA, i, uint64(len(m.Options[iNdEx])))
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.Config) > 0 {
		i -= len(m.Config)
		copy(dAtA[i:], m.Config)
		i = encodeVarintZoneEvents(dAtA, i, uint64(len(m.Config)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Target) > 0 {
		i -= len(m.Target)
		copy(dAtA[i:], m.Target)
		i = encodeVarintZoneEvents(dAtA, i, uint64(len(m.Target)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *SetZoneConfig) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SetZoneConfig) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SetZoneConfig) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.CommonZoneConfigDetails.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintZoneEvents(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	{
		size, err := m.CommonSQLEventDetails.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintZoneEvents(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	{
		size, err := m.CommonEventDetails.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintZoneEvents(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *RemoveZoneConfig) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RemoveZoneConfig) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *RemoveZoneConfig) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.CommonZoneConfigDetails.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintZoneEvents(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	{
		size, err := m.CommonSQLEventDetails.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintZoneEvents(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	{
		size, err := m.CommonEventDetails.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintZoneEvents(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintZoneEvents(dAtA []byte, offset int, v uint64) int {
	offset -= sovZoneEvents(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *CommonZoneConfigDetails) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Target)
	if l > 0 {
		n += 1 + l + sovZoneEvents(uint64(l))
	}
	l = len(m.Config)
	if l > 0 {
		n += 1 + l + sovZoneEvents(uint64(l))
	}
	if len(m.Options) > 0 {
		for _, s := range m.Options {
			l = len(s)
			n += 1 + l + sovZoneEvents(uint64(l))
		}
	}
	return n
}

func (m *SetZoneConfig) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.CommonEventDetails.Size()
	n += 1 + l + sovZoneEvents(uint64(l))
	l = m.CommonSQLEventDetails.Size()
	n += 1 + l + sovZoneEvents(uint64(l))
	l = m.CommonZoneConfigDetails.Size()
	n += 1 + l + sovZoneEvents(uint64(l))
	return n
}

func (m *RemoveZoneConfig) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.CommonEventDetails.Size()
	n += 1 + l + sovZoneEvents(uint64(l))
	l = m.CommonSQLEventDetails.Size()
	n += 1 + l + sovZoneEvents(uint64(l))
	l = m.CommonZoneConfigDetails.Size()
	n += 1 + l + sovZoneEvents(uint64(l))
	return n
}

func sovZoneEvents(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozZoneEvents(x uint64) (n int) {
	return sovZoneEvents(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *CommonZoneConfigDetails) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowZoneEvents
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CommonZoneConfigDetails: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CommonZoneConfigDetails: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Target", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowZoneEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthZoneEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthZoneEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Target = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Config", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowZoneEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthZoneEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthZoneEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Config = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Options", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowZoneEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthZoneEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthZoneEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Options = append(m.Options, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipZoneEvents(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthZoneEvents
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SetZoneConfig) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowZoneEvents
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SetZoneConfig: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SetZoneConfig: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CommonEventDetails", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowZoneEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthZoneEvents
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthZoneEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.CommonEventDetails.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CommonSQLEventDetails", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowZoneEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthZoneEvents
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthZoneEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.CommonSQLEventDetails.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CommonZoneConfigDetails", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowZoneEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthZoneEvents
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthZoneEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.CommonZoneConfigDetails.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipZoneEvents(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthZoneEvents
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *RemoveZoneConfig) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowZoneEvents
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RemoveZoneConfig: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RemoveZoneConfig: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CommonEventDetails", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowZoneEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthZoneEvents
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthZoneEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.CommonEventDetails.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CommonSQLEventDetails", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowZoneEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthZoneEvents
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthZoneEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.CommonSQLEventDetails.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CommonZoneConfigDetails", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowZoneEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthZoneEvents
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthZoneEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.CommonZoneConfigDetails.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipZoneEvents(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthZoneEvents
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipZoneEvents(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowZoneEvents
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowZoneEvents
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowZoneEvents
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthZoneEvents
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupZoneEvents
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthZoneEvents
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthZoneEvents        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowZoneEvents          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupZoneEvents = fmt.Errorf("proto: unexpected end of group")
)
