#!/usr/bin/env python3
"""Generate an affirmative per-file license inventory for distributed engine source."""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
import sys


ROOT = Path(__file__).resolve().parents[1]
ENGINE = ROOT / "engine"
OUTPUT = ROOT / "source" / "license-inventory.json"
LICENSE_NAMES = {"license", "licence", "copying", "notice", "authors", "patents"}
NATIVE_LICENSES = {
  "geos": ("LGPL-2.1-only", "engine/c-deps/geos/COPYING"),
  "jemalloc": ("BSD-2-Clause", "engine/c-deps/jemalloc/COPYING"),
  "libedit": ("BSD-3-Clause", "engine/c-deps/libedit/COPYING"),
  "proj": ("MIT", "engine/c-deps/proj/COPYING"),
}
VENDOR_NOTICE_LICENSES = {
  "vendor/github.com/mattn/go-localereader/": (
    "MIT",
    "engine/licenses/THIRD-PARTY-NOTICES.txt (go-localereader section)",
  ),
}
LIBYAML_DERIVED_FILES = {
  "apic.go",
  "emitterc.go",
  "parserc.go",
  "readerc.go",
  "scannerc.go",
  "writerc.go",
  "yamlh.go",
  "yamlprivateh.go",
}
VENDOR_PREFIX_LICENSES = {
  "vendor/github.com/klauspost/compress/": (
    "BSD-3-Clause",
    "engine/vendor/github.com/klauspost/compress/LICENSE (primary package grant)",
  ),
}
MIXED_VENDOR_LICENSE_DOCUMENTS = {
  "vendor/github.com/apache/thrift/LICENSE",
  "vendor/github.com/apache/arrow/go/arrow/LICENSE.txt",
  "vendor/github.com/klauspost/compress/LICENSE",
  "vendor/go.opentelemetry.io/otel/exporters/jaeger/internal/third_party/thrift/LICENSE",
}


def fail(message: str) -> None:
  print(f"license-inventory error: {message}", file=sys.stderr)
  raise SystemExit(1)


def digest(path: Path) -> str:
  return hashlib.sha256(path.read_bytes()).hexdigest()


def looks_like_license(path: Path) -> bool:
  stem = path.name.lower().split(".", 1)[0]
  return stem in LICENSE_NAMES


def detect_license(text: str, path: Path) -> str:
  lowered = text.lower()
  if "gnu general public license" in lowered and "special exception" in lowered:
    if "built using gnu libtool" in lowered or "gnu libtool" in lowered:
      return "GPL-2.0-or-later WITH Libtool-exception"
    if "autoconf macro" in lowered and "unlimited permission" in lowered:
      return "GPL-3.0-or-later WITH Autoconf-exception-macro"
    if "configuration script generated by autoconf" in lowered:
      if "additional permission under section 7" in lowered:
        return "GPL-3.0-or-later WITH Autoconf-exception-3.0"
      return "GPL-2.0-or-later WITH Autoconf-exception-generic"
  if "mozilla public license" in lowered and "version 2.0" in lowered:
    return "MPL-2.0"
  if "apache license" in lowered and "version 2.0" in lowered:
    return "Apache-2.0"
  if "gnu lesser general public license" in lowered and "version 2.1" in lowered:
    return "LGPL-2.1-or-later" if "any later version" in lowered else "LGPL-2.1-only"
  if "gnu general public license" in lowered and "version 3" in lowered:
    return "GPL-3.0-or-later" if "any later version" in lowered else "GPL-3.0-only"
  if "gnu general public license" in lowered and "version 2" in lowered:
    return "GPL-2.0-or-later" if "any later version" in lowered else "GPL-2.0-only"
  if "permission is hereby granted, free of charge" in lowered:
    return "MIT"
  if "permission to use, copy, modify, and/or distribute" in lowered:
    return "ISC"
  if "redistribution and use in source and binary forms" in lowered:
    if "neither the name" in lowered or "names of its contributors" in lowered:
      return "BSD-3-Clause"
    return "BSD-2-Clause"
  if "postgresql database management system" in lowered or "postgresql global development group" in lowered:
    return "PostgreSQL"
  if "python software foundation license" in lowered:
    return "PSF-2.0"
  if "zlib license" in lowered or "this software is provided 'as-is', without any express or implied warranty" in lowered:
    return "Zlib"
  if "creative commons zero" in lowered or "cc0 1.0 universal" in lowered:
    return "CC0-1.0"
  if "unlicense" in lowered and "public domain" in lowered:
    return "Unlicense"
  return f"LicenseRef-{path.name.replace('.', '-')}-{digest(path)[:12]}"


def classify_native(path: Path, text: str, component: str) -> tuple[str, str]:
  default = NATIVE_LICENSES[component]
  if path == ENGINE / "c-deps" / component / "COPYING":
    return default
  lowered = text.lower()
  embedded_markers = (
    "gnu general public license",
    "gnu lesser general public license",
    "apache license",
    "mozilla public license",
    "permission is hereby granted, free of charge",
    "redistribution and use in source and binary forms",
  )
  if any(marker in lowered for marker in embedded_markers):
    detected = detect_license(text, path)
    if not detected.startswith("LicenseRef-"):
      return detected, f"{path.relative_to(ROOT).as_posix()} (embedded license grant)"
  return default


def nearest_vendor_license(path: Path, licenses_by_parent: dict[Path, list[Path]]) -> Path | None:
  parent = path.parent
  while parent != ENGINE.parent and parent != ROOT:
    candidates = licenses_by_parent.get(parent, [])
    if candidates:
      preferred = [candidate for candidate in candidates if candidate.name.lower().startswith(("license", "copying"))]
      return (preferred or candidates)[0]
    if parent == ENGINE:
      break
    parent = parent.parent
  return None


def classify_vendor(path: Path, licenses_by_parent: dict[Path, list[Path]]) -> tuple[str, str]:
  engine_relative = path.relative_to(ENGINE).as_posix()
  yaml_prefixes = ("vendor/gopkg.in/yaml.v2/", "vendor/gopkg.in/yaml.v3/")
  if engine_relative in MIXED_VENDOR_LICENSE_DOCUMENTS:
    return "LicenseRef-Aggregate-License-Text", path.relative_to(ROOT).as_posix()
  if engine_relative == "vendor/gopkg.in/yaml.v2/LICENSE.libyaml":
    return "MIT", path.relative_to(ROOT).as_posix()
  if engine_relative == "vendor/gopkg.in/yaml.v3/LICENSE":
    return "Apache-2.0 AND MIT", path.relative_to(ROOT).as_posix()
  if engine_relative.startswith(yaml_prefixes) and path.name in LIBYAML_DERIVED_FILES:
    license_path = (
      path.parent / "LICENSE.libyaml"
      if (path.parent / "LICENSE.libyaml").is_file()
      else path.parent / "LICENSE"
    )
    return "MIT", license_path.relative_to(ROOT).as_posix()

  license_path = nearest_vendor_license(path, licenses_by_parent)
  prefix_match = next(
    ((prefix, value) for prefix, value in VENDOR_PREFIX_LICENSES.items()
     if engine_relative.startswith(prefix)),
    None,
  )
  if prefix_match is not None:
    prefix, prefix_license = prefix_match
    package_root = ENGINE / prefix.rstrip("/")
    if license_path is None or license_path.parent == package_root:
      return prefix_license
  if license_path is not None and license_path.parent != path.parent:
    return (
      detect_license(license_path.read_text(encoding="utf-8", errors="ignore"), license_path),
      license_path.relative_to(ROOT).as_posix(),
    )
  if license_path is not None:
    return (
      detect_license(license_path.read_text(encoding="utf-8", errors="ignore"), license_path),
      license_path.relative_to(ROOT).as_posix(),
    )
  fallback = next(
    (value for prefix, value in VENDOR_NOTICE_LICENSES.items() if engine_relative.startswith(prefix)),
    None,
  )
  if fallback is None:
    fail(f"vendored file has no retained ancestor license: {path.relative_to(ROOT).as_posix()}")
  return fallback


def classify_pkg(path: Path, text: str) -> tuple[str, str]:
  relative = path.relative_to(ENGINE).as_posix()
  header = "\n".join(text.splitlines()[:30]).lower()
  if relative.startswith("pkg/geo/geographiclib/geodesic."):
    return "MIT", "GeographicLib MIT/X11 notice in the source header"
  if relative.startswith("pkg/util/tsearch/stopwords/"):
    return "PostgreSQL", "PostgreSQL-derived stopword data; engine/licenses/PostgreSQL.txt"
  if relative.startswith("pkg/geo/geoprojbase/data/"):
    return "MIT", "PROJ data embedded by the transitioned OSS package; engine/c-deps/proj/COPYING"
  if relative.startswith("pkg/security/securitytest/test_certs/"):
    return "Apache-2.0", "public test fixture embedded by the transitioned OSS securitytest package"
  if "business source license" in header and "change date" in header:
    return "Apache-2.0", "BSL change license effective 2026-04-01; engine/licenses/BSL.txt"
  if "apache license" in header:
    return "Apache-2.0", "Apache-2.0 source header"
  if "bsd-style" in header or "redistribution and use in source and binary forms" in header:
    return "BSD-3-Clause", "BSD source header and preserved engine license text"
  if "mit/x11 license" in header or "mit license" in header:
    return "MIT", "MIT source header"
  if "code generated" in text[:1024].lower() or "generated file do not edit" in text[:1024].lower():
    return "Apache-2.0", "generated output of transitioned Apache-2.0 OSS engine source"
  explicit_apache_data = {
    "pkg/build/version.txt",
    "pkg/ui/distoss/assets/.gitkeep",
    "pkg/obsservice/obslib/migrations/sqlmigrations/0001_init.sql",
    "pkg/security/securitytest/test_certs/README.md",
    "pkg/security/securitytest/test_certs/ca.cnf",
    "pkg/security/securitytest/test_certs/regenerate.sh",
  }
  if relative in explicit_apache_data:
    return "Apache-2.0", "data or metadata embedded by a transitioned Apache-2.0 OSS package"
  fail(f"unclassified upstream engine file: engine/{relative}")


def inventory() -> dict:
  license_files = {
    path for path in (ENGINE / "vendor").rglob("*")
    if path.is_file() and looks_like_license(path)
  }
  licenses_by_parent: dict[Path, list[Path]] = {}
  for license_file in sorted(license_files):
    licenses_by_parent.setdefault(license_file.parent, []).append(license_file)
  entries = []
  for path in sorted((path for path in ENGINE.rglob("*") if path.is_file()), key=lambda item: item.as_posix()):
    relative = path.relative_to(ROOT).as_posix()
    try:
      text = path.read_bytes()[:32768].decode("utf-8", "ignore")
    except OSError as error:
      fail(f"cannot read {relative}: {error}")

    engine_relative = path.relative_to(ENGINE)
    if engine_relative.parts[0] == "pkg":
      spdx, basis = classify_pkg(path, text)
    elif engine_relative.parts[0] == "vendor":
      if engine_relative.as_posix() == "vendor/modules.txt":
        spdx, basis = "Apache-2.0", "upstream module metadata for the transitioned OSS source closure"
      else:
        spdx, basis = classify_vendor(path, licenses_by_parent)
    elif engine_relative.parts[0] == "c-deps":
      component = engine_relative.parts[1]
      if component not in NATIVE_LICENSES:
        fail(f"unclassified native dependency: {relative}")
      spdx, basis = classify_native(path, text, component)
    elif engine_relative.parts[0] == "licenses":
      spdx, basis = "LicenseRef-License-Text", "retained license or notice text"
    elif engine_relative.as_posix() in {"go.mod", "go.sum"}:
      spdx, basis = "Apache-2.0", "upstream metadata for the transitioned OSS source closure"
    else:
      fail(f"file is outside the classified engine layout: {relative}")
    entries.append({"path": relative, "sha256": digest(path), "spdx": spdx, "basis": basis})

  return {
    "schemaVersion": 1,
    "upstream": {
      "tag": "v23.1.28",
      "commit": "76e598c9b1c100fd9280b979140b5e377c330a20",
      "bslChangeDate": "2026-04-01",
      "bslChangeLicense": "Apache-2.0",
    },
    "files": entries,
  }


def render() -> str:
  return json.dumps(inventory(), indent=2, sort_keys=True) + "\n"


def main() -> None:
  parser = argparse.ArgumentParser()
  parser.add_argument("--check", action="store_true")
  args = parser.parse_args()
  rendered = render()
  if args.check:
    if not OUTPUT.is_file() or OUTPUT.read_text(encoding="utf-8") != rendered:
      fail("source/license-inventory.json is stale")
    print(f"verified {len(json.loads(rendered)['files'])} affirmatively classified engine files")
    return
  OUTPUT.write_text(rendered, encoding="utf-8")
  print(f"wrote {len(json.loads(rendered)['files'])} license inventory entries")


if __name__ == "__main__":
  main()
